from enum import StrEnum


class IncidentStatus(StrEnum):
    NEW = "NEW"
    PROBLEM_IS_BEING_SOLVED = "PROBLEM_IS_BEING_SOLVED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"


class IncidentPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class InviteScope(StrEnum):
    ORGANIZATION = "ORGANIZATION"
    PROJECT = "PROJECT"


class IncidentLogType(StrEnum):
    COMMENT = "COMMENT"
    STATUS_CHANGED = "STATUS_CHANGED"
    ASSIGNEE_CHANGED = "ASSIGNEE_CHANGED"
    HELPER_ADDED = "HELPER_ADDED"
    HELPER_REMOVED = "HELPER_REMOVED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    CATEGORY_CHANGED = "CATEGORY_CHANGED"
    CREATED = "CREATED"
    CLOSED = "CLOSED"
