/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
    CategoryListResponse,
    CreateCategoryRequest,
    CreatedIdResponse,
    UpdateCategoryRequest,
} from '../models/index';
import {
    CategoryListResponseFromJSON,
    CreateCategoryRequestToJSON,
    CreatedIdResponseFromJSON,
    UpdateCategoryRequestToJSON,
} from '../models/index';

export interface ProjectsProjectIdCategoriesCategoryIdDeleteRequest {
    projectId: string;
    categoryId: string;
}

export interface ProjectsProjectIdCategoriesCategoryIdPatchRequest {
    projectId: string;
    categoryId: string;
    updateCategoryRequest: UpdateCategoryRequest;
}

export interface ProjectsProjectIdCategoriesGetRequest {
    projectId: string;
}

export interface ProjectsProjectIdCategoriesPostRequest {
    projectId: string;
    createCategoryRequest: CreateCategoryRequest;
}

/**
 *
 */
export class CategoriesApi extends runtime.BaseAPI {

    /**
     * Deletes a category when it is not used or after a safe migration.
     * Delete category
     */
    async projectsProjectIdCategoriesCategoryIdDeleteRaw(requestParameters: ProjectsProjectIdCategoriesCategoryIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdCategoriesCategoryIdDelete().'
            );
        }

        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling projectsProjectIdCategoriesCategoryIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/categories/{category_id}`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"category_id"}}`, encodeURIComponent(String(requestParameters['categoryId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a category when it is not used or after a safe migration.
     * Delete category
     */
    async projectsProjectIdCategoriesCategoryIdDelete(requestParameters: ProjectsProjectIdCategoriesCategoryIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsProjectIdCategoriesCategoryIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Updates category name or metadata.
     * Update category
     */
    async projectsProjectIdCategoriesCategoryIdPatchRaw(requestParameters: ProjectsProjectIdCategoriesCategoryIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdCategoriesCategoryIdPatch().'
            );
        }

        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling projectsProjectIdCategoriesCategoryIdPatch().'
            );
        }

        if (requestParameters['updateCategoryRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCategoryRequest',
                'Required parameter "updateCategoryRequest" was null or undefined when calling projectsProjectIdCategoriesCategoryIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/categories/{category_id}`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"category_id"}}`, encodeURIComponent(String(requestParameters['categoryId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCategoryRequestToJSON(requestParameters['updateCategoryRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates category name or metadata.
     * Update category
     */
    async projectsProjectIdCategoriesCategoryIdPatch(requestParameters: ProjectsProjectIdCategoriesCategoryIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsProjectIdCategoriesCategoryIdPatchRaw(requestParameters, initOverrides);
    }

    /**
     * Returns categories available in a project.
     * List project categories
     */
    async projectsProjectIdCategoriesGetRaw(requestParameters: ProjectsProjectIdCategoriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoryListResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdCategoriesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/categories`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoryListResponseFromJSON(jsonValue));
    }

    /**
     * Returns categories available in a project.
     * List project categories
     */
    async projectsProjectIdCategoriesGet(requestParameters: ProjectsProjectIdCategoriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoryListResponse> {
        const response = await this.projectsProjectIdCategoriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a category available for incidents in the project.
     * Create project category
     */
    async projectsProjectIdCategoriesPostRaw(requestParameters: ProjectsProjectIdCategoriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedIdResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdCategoriesPost().'
            );
        }

        if (requestParameters['createCategoryRequest'] == null) {
            throw new runtime.RequiredError(
                'createCategoryRequest',
                'Required parameter "createCategoryRequest" was null or undefined when calling projectsProjectIdCategoriesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/categories`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCategoryRequestToJSON(requestParameters['createCategoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedIdResponseFromJSON(jsonValue));
    }

    /**
     * Creates a category available for incidents in the project.
     * Create project category
     */
    async projectsProjectIdCategoriesPost(requestParameters: ProjectsProjectIdCategoriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedIdResponse> {
        const response = await this.projectsProjectIdCategoriesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
