/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {FeedbackRequest,} from '../models';
import {FeedbackRequestToJSON,} from '../models';

export interface FeedbackPostRequest {
    feedbackRequest: FeedbackRequest;
}

/**
 *
 */
export class FeedbackApi extends runtime.BaseAPI {

    /**
     * Optional contact/feedback endpoint, not required for core incident workflow.
     * Send platform feedback
     */
    async feedbackPostRaw(requestParameters: FeedbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['feedbackRequest'] == null) {
            throw new runtime.RequiredError(
                'feedbackRequest',
                'Required parameter "feedbackRequest" was null or undefined when calling feedbackPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/feedback`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FeedbackRequestToJSON(requestParameters['feedbackRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Optional contact/feedback endpoint, not required for core incident workflow.
     * Send platform feedback
     */
    async feedbackPost(requestParameters: FeedbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.feedbackPostRaw(requestParameters, initOverrides);
    }

}
