/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
    AddCommentRequest,
    AddHelperRequest,
    CommentListResponse,
    CreatedIdResponse,
    CreateIncidentRequest,
    IncidentDetailsResponse,
    IncidentListResponse,
    IncidentLogListResponse,
    IncidentLogType,
    IncidentPriority,
    IncidentStatus,
    UpdateIncidentAssigneeRequest,
    UpdateIncidentCategoryRequest,
    UpdateIncidentPriorityRequest,
    UpdateIncidentStatusRequest,
} from '../models/index';
import {
    AddCommentRequestToJSON,
    AddHelperRequestToJSON,
    CommentListResponseFromJSON,
    CreatedIdResponseFromJSON,
    CreateIncidentRequestToJSON,
    IncidentDetailsResponseFromJSON,
    IncidentListResponseFromJSON,
    IncidentLogListResponseFromJSON,
    UpdateIncidentAssigneeRequestToJSON,
    UpdateIncidentCategoryRequestToJSON,
    UpdateIncidentPriorityRequestToJSON,
    UpdateIncidentStatusRequestToJSON,
} from '../models/index';

export interface IncidentsHistoryGetRequest {
    projectId?: string;
    type?: IncidentLogType;
    offset?: number;
    limit?: number;
}

export interface IncidentsIncidentIdAssigneePatchRequest {
    incidentId: string;
    updateIncidentAssigneeRequest: UpdateIncidentAssigneeRequest;
}

export interface IncidentsIncidentIdCategoryPatchRequest {
    incidentId: string;
    updateIncidentCategoryRequest: UpdateIncidentCategoryRequest;
}

export interface IncidentsIncidentIdClosePostRequest {
    incidentId: string;
}

export interface IncidentsIncidentIdCommentsGetRequest {
    incidentId: string;
}

export interface IncidentsIncidentIdCommentsPostRequest {
    incidentId: string;
    addCommentRequest: AddCommentRequest;
}

export interface IncidentsIncidentIdGetRequest {
    incidentId: string;
}

export interface IncidentsIncidentIdHelpersHelperIdDeleteRequest {
    incidentId: string;
    helperId: string;
}

export interface IncidentsIncidentIdHelpersPostRequest {
    incidentId: string;
    addHelperRequest: AddHelperRequest;
}

export interface IncidentsIncidentIdLogsGetRequest {
    incidentId: string;
    offset?: number;
    limit?: number;
}

export interface IncidentsIncidentIdPriorityPatchRequest {
    incidentId: string;
    updateIncidentPriorityRequest: UpdateIncidentPriorityRequest;
}

export interface IncidentsIncidentIdRequestReassignmentPostRequest {
    incidentId: string;
}

export interface IncidentsIncidentIdStatusPatchRequest {
    incidentId: string;
    updateIncidentStatusRequest: UpdateIncidentStatusRequest;
}

export interface ProjectsProjectIdIncidentsGetRequest {
    projectId: string;
    offset?: number;
    limit?: number;
    status?: IncidentStatus;
    priority?: IncidentPriority;
    assigneeId?: string;
}

export interface ProjectsProjectIdIncidentsPostRequest {
    projectId: string;
    createIncidentRequest: CreateIncidentRequest;
}

/**
 *
 */
export class IncidentsApi extends runtime.BaseAPI {

    /**
     * Get user-centric incident log history
     */
    async incidentsHistoryGetRaw(requestParameters: IncidentsHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentLogListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/history`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentLogListResponseFromJSON(jsonValue));
    }

    /**
     * Get user-centric incident log history
     */
    async incidentsHistoryGet(requestParameters: IncidentsHistoryGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentLogListResponse> {
        const response = await this.incidentsHistoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change primary assignee
     */
    async incidentsIncidentIdAssigneePatchRaw(requestParameters: IncidentsIncidentIdAssigneePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdAssigneePatch().'
            );
        }

        if (requestParameters['updateIncidentAssigneeRequest'] == null) {
            throw new runtime.RequiredError(
                'updateIncidentAssigneeRequest',
                'Required parameter "updateIncidentAssigneeRequest" was null or undefined when calling incidentsIncidentIdAssigneePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/assignee`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateIncidentAssigneeRequestToJSON(requestParameters['updateIncidentAssigneeRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Change primary assignee
     */
    async incidentsIncidentIdAssigneePatch(requestParameters: IncidentsIncidentIdAssigneePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incidentsIncidentIdAssigneePatchRaw(requestParameters, initOverrides);
    }

    /**
     * Change incident category
     */
    async incidentsIncidentIdCategoryPatchRaw(requestParameters: IncidentsIncidentIdCategoryPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdCategoryPatch().'
            );
        }

        if (requestParameters['updateIncidentCategoryRequest'] == null) {
            throw new runtime.RequiredError(
                'updateIncidentCategoryRequest',
                'Required parameter "updateIncidentCategoryRequest" was null or undefined when calling incidentsIncidentIdCategoryPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/category`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateIncidentCategoryRequestToJSON(requestParameters['updateIncidentCategoryRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Change incident category
     */
    async incidentsIncidentIdCategoryPatch(requestParameters: IncidentsIncidentIdCategoryPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incidentsIncidentIdCategoryPatchRaw(requestParameters, initOverrides);
    }

    /**
     * Close incident explicitly
     */
    async incidentsIncidentIdClosePostRaw(requestParameters: IncidentsIncidentIdClosePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdClosePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/close`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Close incident explicitly
     */
    async incidentsIncidentIdClosePost(requestParameters: IncidentsIncidentIdClosePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incidentsIncidentIdClosePostRaw(requestParameters, initOverrides);
    }

    /**
     * List incident comments
     */
    async incidentsIncidentIdCommentsGetRaw(requestParameters: IncidentsIncidentIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentListResponse>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdCommentsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/comments`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentListResponseFromJSON(jsonValue));
    }

    /**
     * List incident comments
     */
    async incidentsIncidentIdCommentsGet(requestParameters: IncidentsIncidentIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentListResponse> {
        const response = await this.incidentsIncidentIdCommentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add incident comment
     */
    async incidentsIncidentIdCommentsPostRaw(requestParameters: IncidentsIncidentIdCommentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedIdResponse>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdCommentsPost().'
            );
        }

        if (requestParameters['addCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'addCommentRequest',
                'Required parameter "addCommentRequest" was null or undefined when calling incidentsIncidentIdCommentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/comments`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddCommentRequestToJSON(requestParameters['addCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedIdResponseFromJSON(jsonValue));
    }

    /**
     * Add incident comment
     */
    async incidentsIncidentIdCommentsPost(requestParameters: IncidentsIncidentIdCommentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedIdResponse> {
        const response = await this.incidentsIncidentIdCommentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get incident details
     */
    async incidentsIncidentIdGetRaw(requestParameters: IncidentsIncidentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentDetailsResponse>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentDetailsResponseFromJSON(jsonValue));
    }

    /**
     * Get incident details
     */
    async incidentsIncidentIdGet(requestParameters: IncidentsIncidentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentDetailsResponse> {
        const response = await this.incidentsIncidentIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove helper from incident
     */
    async incidentsIncidentIdHelpersHelperIdDeleteRaw(requestParameters: IncidentsIncidentIdHelpersHelperIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdHelpersHelperIdDelete().'
            );
        }

        if (requestParameters['helperId'] == null) {
            throw new runtime.RequiredError(
                'helperId',
                'Required parameter "helperId" was null or undefined when calling incidentsIncidentIdHelpersHelperIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/helpers/{helper_id}`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))).replace(`{${"helper_id"}}`, encodeURIComponent(String(requestParameters['helperId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove helper from incident
     */
    async incidentsIncidentIdHelpersHelperIdDelete(requestParameters: IncidentsIncidentIdHelpersHelperIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incidentsIncidentIdHelpersHelperIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Add helper to incident
     */
    async incidentsIncidentIdHelpersPostRaw(requestParameters: IncidentsIncidentIdHelpersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdHelpersPost().'
            );
        }

        if (requestParameters['addHelperRequest'] == null) {
            throw new runtime.RequiredError(
                'addHelperRequest',
                'Required parameter "addHelperRequest" was null or undefined when calling incidentsIncidentIdHelpersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/helpers`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddHelperRequestToJSON(requestParameters['addHelperRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add helper to incident
     */
    async incidentsIncidentIdHelpersPost(requestParameters: IncidentsIncidentIdHelpersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incidentsIncidentIdHelpersPostRaw(requestParameters, initOverrides);
    }

    /**
     * List incident audit logs
     */
    async incidentsIncidentIdLogsGetRaw(requestParameters: IncidentsIncidentIdLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentLogListResponse>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdLogsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/logs`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentLogListResponseFromJSON(jsonValue));
    }

    /**
     * List incident audit logs
     */
    async incidentsIncidentIdLogsGet(requestParameters: IncidentsIncidentIdLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentLogListResponse> {
        const response = await this.incidentsIncidentIdLogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change incident priority
     */
    async incidentsIncidentIdPriorityPatchRaw(requestParameters: IncidentsIncidentIdPriorityPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdPriorityPatch().'
            );
        }

        if (requestParameters['updateIncidentPriorityRequest'] == null) {
            throw new runtime.RequiredError(
                'updateIncidentPriorityRequest',
                'Required parameter "updateIncidentPriorityRequest" was null or undefined when calling incidentsIncidentIdPriorityPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/priority`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateIncidentPriorityRequestToJSON(requestParameters['updateIncidentPriorityRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Change incident priority
     */
    async incidentsIncidentIdPriorityPatch(requestParameters: IncidentsIncidentIdPriorityPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incidentsIncidentIdPriorityPatchRaw(requestParameters, initOverrides);
    }

    /**
     * Request solver reassignment
     */
    async incidentsIncidentIdRequestReassignmentPostRaw(requestParameters: IncidentsIncidentIdRequestReassignmentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdRequestReassignmentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/request-reassignment`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Request solver reassignment
     */
    async incidentsIncidentIdRequestReassignmentPost(requestParameters: IncidentsIncidentIdRequestReassignmentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incidentsIncidentIdRequestReassignmentPostRaw(requestParameters, initOverrides);
    }

    /**
     * Change incident status
     */
    async incidentsIncidentIdStatusPatchRaw(requestParameters: IncidentsIncidentIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['incidentId'] == null) {
            throw new runtime.RequiredError(
                'incidentId',
                'Required parameter "incidentId" was null or undefined when calling incidentsIncidentIdStatusPatch().'
            );
        }

        if (requestParameters['updateIncidentStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'updateIncidentStatusRequest',
                'Required parameter "updateIncidentStatusRequest" was null or undefined when calling incidentsIncidentIdStatusPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/{incident_id}/status`.replace(`{${"incident_id"}}`, encodeURIComponent(String(requestParameters['incidentId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateIncidentStatusRequestToJSON(requestParameters['updateIncidentStatusRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Change incident status
     */
    async incidentsIncidentIdStatusPatch(requestParameters: IncidentsIncidentIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incidentsIncidentIdStatusPatchRaw(requestParameters, initOverrides);
    }

    /**
     * List incidents assigned to current user
     */
    async incidentsMyAssignedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/my-assigned`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentListResponseFromJSON(jsonValue));
    }

    /**
     * List incidents assigned to current user
     */
    async incidentsMyAssignedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentListResponse> {
        const response = await this.incidentsMyAssignedGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List incidents reported by current user
     */
    async incidentsMyReportedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/incidents/my-reported`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentListResponseFromJSON(jsonValue));
    }

    /**
     * List incidents reported by current user
     */
    async incidentsMyReportedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentListResponse> {
        const response = await this.incidentsMyReportedGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List incidents in project
     */
    async projectsProjectIdIncidentsGetRaw(requestParameters: ProjectsProjectIdIncidentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentListResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdIncidentsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['priority'] != null) {
            queryParameters['priority'] = requestParameters['priority'];
        }

        if (requestParameters['assigneeId'] != null) {
            queryParameters['assignee_id'] = requestParameters['assigneeId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/incidents`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentListResponseFromJSON(jsonValue));
    }

    /**
     * List incidents in project
     */
    async projectsProjectIdIncidentsGet(requestParameters: ProjectsProjectIdIncidentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentListResponse> {
        const response = await this.projectsProjectIdIncidentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create incident
     */
    async projectsProjectIdIncidentsPostRaw(requestParameters: ProjectsProjectIdIncidentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedIdResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdIncidentsPost().'
            );
        }

        if (requestParameters['createIncidentRequest'] == null) {
            throw new runtime.RequiredError(
                'createIncidentRequest',
                'Required parameter "createIncidentRequest" was null or undefined when calling projectsProjectIdIncidentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/incidents`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateIncidentRequestToJSON(requestParameters['createIncidentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedIdResponseFromJSON(jsonValue));
    }

    /**
     * Create incident
     */
    async projectsProjectIdIncidentsPost(requestParameters: ProjectsProjectIdIncidentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedIdResponse> {
        const response = await this.projectsProjectIdIncidentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
