/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
    CreateProjectInviteRequest,
    InvitePreviewResponse,
    InviteResponse,
    JoinByInviteRequest,
} from '../models/index';
import {
    CreateProjectInviteRequestToJSON,
    InvitePreviewResponseFromJSON,
    InviteResponseFromJSON,
    JoinByInviteRequestToJSON,
} from '../models/index';

export interface InvitesTokenDeleteRequest {
    token: string;
}

export interface InvitesTokenGetRequest {
    token: string;
}

export interface ProjectsJoinPostRequest {
    joinByInviteRequest: JoinByInviteRequest;
}

export interface ProjectsProjectIdInvitesPostRequest {
    projectId: string;
    createProjectInviteRequest: CreateProjectInviteRequest;
}

/**
 *
 */
export class InvitationsApi extends runtime.BaseAPI {

    /**
     * Creator, project owner, or org owner only.
     * Revoke invite
     */
    async invitesTokenDeleteRaw(requestParameters: InvitesTokenDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling invitesTokenDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/invites/{token}`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creator, project owner, or org owner only.
     * Revoke invite
     */
    async invitesTokenDelete(requestParameters: InvitesTokenDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.invitesTokenDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * No auth required. Lets frontend validate the invite link before the user logs in.
     * Preview invite before accepting
     */
    async invitesTokenGetRaw(requestParameters: InvitesTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitePreviewResponse>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling invitesTokenGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/invites/{token}`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitePreviewResponseFromJSON(jsonValue));
    }

    /**
     * No auth required. Lets frontend validate the invite link before the user logs in.
     * Preview invite before accepting
     */
    async invitesTokenGet(requestParameters: InvitesTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitePreviewResponse> {
        const response = await this.invitesTokenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Join project using invite token
     */
    async projectsJoinPostRaw(requestParameters: ProjectsJoinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['joinByInviteRequest'] == null) {
            throw new runtime.RequiredError(
                'joinByInviteRequest',
                'Required parameter "joinByInviteRequest" was null or undefined when calling projectsJoinPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/join`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoinByInviteRequestToJSON(requestParameters['joinByInviteRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Join project using invite token
     */
    async projectsJoinPost(requestParameters: ProjectsJoinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsJoinPostRaw(requestParameters, initOverrides);
    }

    /**
     * Generates an invite token for joining a specific project. Owner only.
     * Create project invite
     */
    async projectsProjectIdInvitesPostRaw(requestParameters: ProjectsProjectIdInvitesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InviteResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdInvitesPost().'
            );
        }

        if (requestParameters['createProjectInviteRequest'] == null) {
            throw new runtime.RequiredError(
                'createProjectInviteRequest',
                'Required parameter "createProjectInviteRequest" was null or undefined when calling projectsProjectIdInvitesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/invites`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProjectInviteRequestToJSON(requestParameters['createProjectInviteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InviteResponseFromJSON(jsonValue));
    }

    /**
     * Generates an invite token for joining a specific project. Owner only.
     * Create project invite
     */
    async projectsProjectIdInvitesPost(requestParameters: ProjectsProjectIdInvitesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InviteResponse> {
        const response = await this.projectsProjectIdInvitesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
