/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {CreateInviteRequest, InvitePreviewResponse, InviteResponse, JoinByInviteRequest,} from '../models';
import {
    CreateInviteRequestToJSON,
    InvitePreviewResponseFromJSON,
    InviteResponseFromJSON,
    JoinByInviteRequestToJSON,
} from '../models';

export interface InvitesTokenGetRequest {
    token: string;
}

export interface ProjectsJoinPostRequest {
    joinByInviteRequest: JoinByInviteRequest;
}

export interface ProjectsProjectIdInvitesPostRequest {
    projectId: string;
    createInviteRequest: CreateInviteRequest;
}

/**
 *
 */
export class InvitationsApi extends runtime.BaseAPI {

    /**
     * Lets frontend validate an invite link and preview whether it grants access to an organization or a project.
     * Inspect invite before accepting
     */
    async invitesTokenGetRaw(requestParameters: InvitesTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitePreviewResponse>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling invitesTokenGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/invites/{token}`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitePreviewResponseFromJSON(jsonValue));
    }

    /**
     * Lets frontend validate an invite link and preview whether it grants access to an organization or a project.
     * Inspect invite before accepting
     */
    async invitesTokenGet(requestParameters: InvitesTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitePreviewResponse> {
        const response = await this.invitesTokenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Accepts a project invite and joins the current user to the project.
     * Join project using invite token
     */
    async projectsJoinPostRaw(requestParameters: ProjectsJoinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['joinByInviteRequest'] == null) {
            throw new runtime.RequiredError(
                'joinByInviteRequest',
                'Required parameter "joinByInviteRequest" was null or undefined when calling projectsJoinPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects/join`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoinByInviteRequestToJSON(requestParameters['joinByInviteRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Accepts a project invite and joins the current user to the project.
     * Join project using invite token
     */
    async projectsJoinPost(requestParameters: ProjectsJoinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsJoinPostRaw(requestParameters, initOverrides);
    }

    /**
     * Generates an invite token that lets a user join a specific project directly.
     * Create project invite
     */
    async projectsProjectIdInvitesPostRaw(requestParameters: ProjectsProjectIdInvitesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InviteResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdInvitesPost().'
            );
        }

        if (requestParameters['createInviteRequest'] == null) {
            throw new runtime.RequiredError(
                'createInviteRequest',
                'Required parameter "createInviteRequest" was null or undefined when calling projectsProjectIdInvitesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects/{projectId}/invites`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInviteRequestToJSON(requestParameters['createInviteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InviteResponseFromJSON(jsonValue));
    }

    /**
     * Generates an invite token that lets a user join a specific project directly.
     * Create project invite
     */
    async projectsProjectIdInvitesPost(requestParameters: ProjectsProjectIdInvitesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InviteResponse> {
        const response = await this.projectsProjectIdInvitesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
