/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
    CreatedIdResponse,
    CreateOrganizationRequest,
    CreateOrgInviteRequest,
    InviteResponse,
    JoinByInviteRequest,
    OrganizationResponse,
} from '../models/index';
import {
    CreatedIdResponseFromJSON,
    CreateOrganizationRequestToJSON,
    CreateOrgInviteRequestToJSON,
    InviteResponseFromJSON,
    JoinByInviteRequestToJSON,
    OrganizationResponseFromJSON,
} from '../models/index';

export interface OrganizationInvitesPostRequest {
    createOrgInviteRequest: CreateOrgInviteRequest;
}

export interface OrganizationJoinPostRequest {
    joinByInviteRequest: JoinByInviteRequest;
}

export interface OrganizationPostRequest {
    createOrganizationRequest: CreateOrganizationRequest;
}

/**
 *
 */
export class OrganizationApi extends runtime.BaseAPI {

    /**
     * Get current user\'s organization
     */
    async organizationGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organization`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationResponseFromJSON(jsonValue));
    }

    /**
     * Get current user\'s organization
     */
    async organizationGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationResponse> {
        const response = await this.organizationGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Generates an invite token for joining the current organization. Organization owner only.
     * Create organization invite
     */
    async organizationInvitesPostRaw(requestParameters: OrganizationInvitesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InviteResponse>> {
        if (requestParameters['createOrgInviteRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrgInviteRequest',
                'Required parameter "createOrgInviteRequest" was null or undefined when calling organizationInvitesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organization/invites`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrgInviteRequestToJSON(requestParameters['createOrgInviteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InviteResponseFromJSON(jsonValue));
    }

    /**
     * Generates an invite token for joining the current organization. Organization owner only.
     * Create organization invite
     */
    async organizationInvitesPost(requestParameters: OrganizationInvitesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InviteResponse> {
        const response = await this.organizationInvitesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Join organization using invite token
     */
    async organizationJoinPostRaw(requestParameters: OrganizationJoinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['joinByInviteRequest'] == null) {
            throw new runtime.RequiredError(
                'joinByInviteRequest',
                'Required parameter "joinByInviteRequest" was null or undefined when calling organizationJoinPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organization/join`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoinByInviteRequestToJSON(requestParameters['joinByInviteRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Join organization using invite token
     */
    async organizationJoinPost(requestParameters: OrganizationJoinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.organizationJoinPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates an organization and assigns the current user as owner. Fails if user already belongs to an organization.
     * Create organization
     */
    async organizationPostRaw(requestParameters: OrganizationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedIdResponse>> {
        if (requestParameters['createOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrganizationRequest',
                'Required parameter "createOrganizationRequest" was null or undefined when calling organizationPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organization`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationRequestToJSON(requestParameters['createOrganizationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedIdResponseFromJSON(jsonValue));
    }

    /**
     * Creates an organization and assigns the current user as owner. Fails if user already belongs to an organization.
     * Create organization
     */
    async organizationPost(requestParameters: OrganizationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedIdResponse> {
        const response = await this.organizationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
