/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {ProfileResponse, UpdateProfileRequest, UserSearchResponse,} from '../models';
import {ProfileResponseFromJSON, UpdateProfileRequestToJSON, UserSearchResponseFromJSON,} from '../models';

export interface ProfilesMePatchRequest {
    updateProfileRequest: UpdateProfileRequest;
}

export interface UsersSearchGetRequest {
    query: string;
}

/**
 *
 */
export class ProfilesApi extends runtime.BaseAPI {

    /**
     * Returns editable profile data of the current user.
     * Get current user\'s profile
     */
    async profilesMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/profiles/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileResponseFromJSON(jsonValue));
    }

    /**
     * Returns editable profile data of the current user.
     * Get current user\'s profile
     */
    async profilesMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileResponse> {
        const response = await this.profilesMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Updates optional user profile fields such as bio or display preferences.
     * Update current user\'s profile
     */
    async profilesMePatchRaw(requestParameters: ProfilesMePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['updateProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProfileRequest',
                'Required parameter "updateProfileRequest" was null or undefined when calling profilesMePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/profiles/me`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProfileRequestToJSON(requestParameters['updateProfileRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates optional user profile fields such as bio or display preferences.
     * Update current user\'s profile
     */
    async profilesMePatch(requestParameters: ProfilesMePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.profilesMePatchRaw(requestParameters, initOverrides);
    }

    /**
     * Convenience endpoint useful for assignment dialogs and member lookup.
     * Search users by username or partial text
     */
    async usersSearchGetRaw(requestParameters: UsersSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserSearchResponse>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling usersSearchGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserSearchResponseFromJSON(jsonValue));
    }

    /**
     * Convenience endpoint useful for assignment dialogs and member lookup.
     * Search users by username or partial text
     */
    async usersSearchGet(requestParameters: UsersSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserSearchResponse> {
        const response = await this.usersSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
