/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
    AddProjectMemberRequest,
    AssignRoleRequest,
    CreatedIdResponse,
    CreateProjectRequest,
    ProjectListResponse,
    ProjectMemberListResponse,
    ProjectResponse,
    UpdateProjectRequest,
} from '../models';
import {
    AddProjectMemberRequestToJSON,
    AssignRoleRequestToJSON,
    CreatedIdResponseFromJSON,
    CreateProjectRequestToJSON,
    ProjectListResponseFromJSON,
    ProjectMemberListResponseFromJSON,
    ProjectResponseFromJSON,
    UpdateProjectRequestToJSON,
} from '../models';

export interface ProjectsGetRequest {
    scope?: ProjectsGetScopeEnum;
}

export interface ProjectsPostRequest {
    createProjectRequest: CreateProjectRequest;
}

export interface ProjectsProjectIdGetRequest {
    projectId: string;
}

export interface ProjectsProjectIdMembersGetRequest {
    projectId: string;
}

export interface ProjectsProjectIdMembersPostRequest {
    projectId: string;
    addProjectMemberRequest: AddProjectMemberRequest;
}

export interface ProjectsProjectIdMembersUserIdRolePatchRequest {
    projectId: string;
    userId: string;
    assignRoleRequest: AssignRoleRequest;
}

export interface ProjectsProjectIdPatchRequest {
    projectId: string;
    updateProjectRequest: UpdateProjectRequest;
}

/**
 *
 */
export class ProjectsApi extends runtime.BaseAPI {

    /**
     * Returns private projects and organization projects visible to the current user.
     * List projects visible to current user
     */
    async projectsGetRaw(requestParameters: ProjectsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectListResponseFromJSON(jsonValue));
    }

    /**
     * Returns private projects and organization projects visible to the current user.
     * List projects visible to current user
     */
    async projectsGet(requestParameters: ProjectsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectListResponse> {
        const response = await this.projectsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a project. Project scope can be PRIVATE or ORGANIZATION. A user may have many projects, but organization projects must belong to the user\'s single organization.
     * Create project
     */
    async projectsPostRaw(requestParameters: ProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedIdResponse>> {
        if (requestParameters['createProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'createProjectRequest',
                'Required parameter "createProjectRequest" was null or undefined when calling projectsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProjectRequestToJSON(requestParameters['createProjectRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedIdResponseFromJSON(jsonValue));
    }

    /**
     * Creates a project. Project scope can be PRIVATE or ORGANIZATION. A user may have many projects, but organization projects must belong to the user\'s single organization.
     * Create project
     */
    async projectsPost(requestParameters: ProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedIdResponse> {
        const response = await this.projectsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns project metadata visible to the current user.
     * Get project details
     */
    async projectsProjectIdGetRaw(requestParameters: ProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectResponseFromJSON(jsonValue));
    }

    /**
     * Returns project metadata visible to the current user.
     * Get project details
     */
    async projectsProjectIdGet(requestParameters: ProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectResponse> {
        const response = await this.projectsProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns project members with their single assigned role in that project.
     * List project members
     */
    async projectsProjectIdMembersGetRaw(requestParameters: ProjectsProjectIdMembersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectMemberListResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdMembersGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/members`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectMemberListResponseFromJSON(jsonValue));
    }

    /**
     * Returns project members with their single assigned role in that project.
     * List project members
     */
    async projectsProjectIdMembersGet(requestParameters: ProjectsProjectIdMembersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectMemberListResponse> {
        const response = await this.projectsProjectIdMembersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds a user to a project and assigns exactly one role in that project.
     * Add user to project
     */
    async projectsProjectIdMembersPostRaw(requestParameters: ProjectsProjectIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdMembersPost().'
            );
        }

        if (requestParameters['addProjectMemberRequest'] == null) {
            throw new runtime.RequiredError(
                'addProjectMemberRequest',
                'Required parameter "addProjectMemberRequest" was null or undefined when calling projectsProjectIdMembersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects/{projectId}/members`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddProjectMemberRequestToJSON(requestParameters['addProjectMemberRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Adds a user to a project and assigns exactly one role in that project.
     * Add user to project
     */
    async projectsProjectIdMembersPost(requestParameters: ProjectsProjectIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsProjectIdMembersPostRaw(requestParameters, initOverrides);
    }

    /**
     * Changes the single assigned role of a project member.
     * Change user\'s role in project
     */
    async projectsProjectIdMembersUserIdRolePatchRaw(requestParameters: ProjectsProjectIdMembersUserIdRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdMembersUserIdRolePatch().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling projectsProjectIdMembersUserIdRolePatch().'
            );
        }

        if (requestParameters['assignRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'assignRoleRequest',
                'Required parameter "assignRoleRequest" was null or undefined when calling projectsProjectIdMembersUserIdRolePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects/{projectId}/members/{userId}/role`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AssignRoleRequestToJSON(requestParameters['assignRoleRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Changes the single assigned role of a project member.
     * Change user\'s role in project
     */
    async projectsProjectIdMembersUserIdRolePatch(requestParameters: ProjectsProjectIdMembersUserIdRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsProjectIdMembersUserIdRolePatchRaw(requestParameters, initOverrides);
    }

    /**
     * Allows authorized users to update project name and description.
     * Update project metadata
     */
    async projectsProjectIdPatchRaw(requestParameters: ProjectsProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdPatch().'
            );
        }

        if (requestParameters['updateProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProjectRequest',
                'Required parameter "updateProjectRequest" was null or undefined when calling projectsProjectIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProjectRequestToJSON(requestParameters['updateProjectRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Allows authorized users to update project name and description.
     * Update project metadata
     */
    async projectsProjectIdPatch(requestParameters: ProjectsProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsProjectIdPatchRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const ProjectsGetScopeEnum = {
    Private: 'PRIVATE',
    Organization: 'ORGANIZATION'
} as const;
export type ProjectsGetScopeEnum = typeof ProjectsGetScopeEnum[keyof typeof ProjectsGetScopeEnum];
