/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
    CreatedIdResponse,
    CreateRoleRequest,
    RoleListResponse,
    RoleResponse,
    UpdateRoleRequest,
} from '../models/index';
import {
    CreatedIdResponseFromJSON,
    CreateRoleRequestToJSON,
    RoleListResponseFromJSON,
    RoleResponseFromJSON,
    UpdateRoleRequestToJSON,
} from '../models/index';

export interface ProjectsProjectIdRolesGetRequest {
    projectId: string;
}

export interface ProjectsProjectIdRolesPostRequest {
    projectId: string;
    createRoleRequest: CreateRoleRequest;
}

export interface ProjectsProjectIdRolesRoleIdGetRequest {
    projectId: string;
    roleId: string;
}

export interface ProjectsProjectIdRolesRoleIdPatchRequest {
    projectId: string;
    roleId: string;
    updateRoleRequest: UpdateRoleRequest;
}

/**
 *
 */
export class RolesApi extends runtime.BaseAPI {

    /**
     * List project roles
     */
    async projectsProjectIdRolesGetRaw(requestParameters: ProjectsProjectIdRolesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleListResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdRolesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/roles`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleListResponseFromJSON(jsonValue));
    }

    /**
     * List project roles
     */
    async projectsProjectIdRolesGet(requestParameters: ProjectsProjectIdRolesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleListResponse> {
        const response = await this.projectsProjectIdRolesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Owner only.
     * Create custom project role
     */
    async projectsProjectIdRolesPostRaw(requestParameters: ProjectsProjectIdRolesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedIdResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdRolesPost().'
            );
        }

        if (requestParameters['createRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'createRoleRequest',
                'Required parameter "createRoleRequest" was null or undefined when calling projectsProjectIdRolesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/roles`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRoleRequestToJSON(requestParameters['createRoleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedIdResponseFromJSON(jsonValue));
    }

    /**
     * Owner only.
     * Create custom project role
     */
    async projectsProjectIdRolesPost(requestParameters: ProjectsProjectIdRolesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedIdResponse> {
        const response = await this.projectsProjectIdRolesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get role details
     */
    async projectsProjectIdRolesRoleIdGetRaw(requestParameters: ProjectsProjectIdRolesRoleIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdRolesRoleIdGet().'
            );
        }

        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling projectsProjectIdRolesRoleIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/roles/{role_id}`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"role_id"}}`, encodeURIComponent(String(requestParameters['roleId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleResponseFromJSON(jsonValue));
    }

    /**
     * Get role details
     */
    async projectsProjectIdRolesRoleIdGet(requestParameters: ProjectsProjectIdRolesRoleIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleResponse> {
        const response = await this.projectsProjectIdRolesRoleIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Owner only.
     * Update role definition
     */
    async projectsProjectIdRolesRoleIdPatchRaw(requestParameters: ProjectsProjectIdRolesRoleIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdRolesRoleIdPatch().'
            );
        }

        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling projectsProjectIdRolesRoleIdPatch().'
            );
        }

        if (requestParameters['updateRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateRoleRequest',
                'Required parameter "updateRoleRequest" was null or undefined when calling projectsProjectIdRolesRoleIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/roles/{role_id}`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"role_id"}}`, encodeURIComponent(String(requestParameters['roleId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRoleRequestToJSON(requestParameters['updateRoleRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Owner only.
     * Update role definition
     */
    async projectsProjectIdRolesRoleIdPatch(requestParameters: ProjectsProjectIdRolesRoleIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsProjectIdRolesRoleIdPatchRaw(requestParameters, initOverrides);
    }

}
