/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AddCommentRequest
 */
export interface AddCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof AddCommentRequest
     */
    content: string;
}

/**
 * Check if a given object implements the AddCommentRequest interface.
 */
export function instanceOfAddCommentRequest(value: object): value is AddCommentRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function AddCommentRequestFromJSON(json: any): AddCommentRequest {
    return AddCommentRequestFromJSONTyped(json, false);
}

export function AddCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function AddCommentRequestToJSON(value?: AddCommentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
    };
}

