/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AddHelperRequest
 */
export interface AddHelperRequest {
    /**
     * 
     * @type {string}
     * @memberof AddHelperRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the AddHelperRequest interface.
 */
export function instanceOfAddHelperRequest(value: object): value is AddHelperRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AddHelperRequestFromJSON(json: any): AddHelperRequest {
    return AddHelperRequestFromJSONTyped(json, false);
}

export function AddHelperRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddHelperRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function AddHelperRequestToJSON(value?: AddHelperRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
    };
}

