/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddProjectMemberRequest
 */
export interface AddProjectMemberRequest {
    /**
     *
     * @type {string}
     * @memberof AddProjectMemberRequest
     */
    userId: string;
    /**
     *
     * @type {string}
     * @memberof AddProjectMemberRequest
     */
    roleId: string;
}

/**
 * Check if a given object implements the AddProjectMemberRequest interface.
 */
export function instanceOfAddProjectMemberRequest(value: object): value is AddProjectMemberRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    return true;
}

export function AddProjectMemberRequestFromJSON(json: any): AddProjectMemberRequest {
    return AddProjectMemberRequestFromJSONTyped(json, false);
}

export function AddProjectMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddProjectMemberRequest {
    if (json == null) {
        return json;
    }
    return {

        'userId': json['user_id'],
        'roleId': json['role_id'],
    };
}

export function AddProjectMemberRequestToJSON(value?: AddProjectMemberRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'user_id': value['userId'],
        'role_id': value['roleId'],
    };
}

