/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AssignRoleRequest
 */
export interface AssignRoleRequest {
    /**
     *
     * @type {string}
     * @memberof AssignRoleRequest
     */
    roleId: string;
}

/**
 * Check if a given object implements the AssignRoleRequest interface.
 */
export function instanceOfAssignRoleRequest(value: object): value is AssignRoleRequest {
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    return true;
}

export function AssignRoleRequestFromJSON(json: any): AssignRoleRequest {
    return AssignRoleRequestFromJSONTyped(json, false);
}

export function AssignRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignRoleRequest {
    if (json == null) {
        return json;
    }
    return {

        'roleId': json['roleId'],
    };
}

export function AssignRoleRequestToJSON(value?: AssignRoleRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'roleId': value['roleId'],
    };
}

