/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {CategoryResponse} from './CategoryResponse';
import {CategoryResponseFromJSON, CategoryResponseToJSON,} from './CategoryResponse';

/**
 *
 * @export
 * @interface CategoryListResponse
 */
export interface CategoryListResponse {
    /**
     *
     * @type {Array<CategoryResponse>}
     * @memberof CategoryListResponse
     */
    items: Array<CategoryResponse>;
    /**
     *
     * @type {number}
     * @memberof CategoryListResponse
     */
    total: number;
    /**
     *
     * @type {number}
     * @memberof CategoryListResponse
     */
    offset: number;
    /**
     *
     * @type {number}
     * @memberof CategoryListResponse
     */
    limit: number;
}

/**
 * Check if a given object implements the CategoryListResponse interface.
 */
export function instanceOfCategoryListResponse(value: object): value is CategoryListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function CategoryListResponseFromJSON(json: any): CategoryListResponse {
    return CategoryListResponseFromJSONTyped(json, false);
}

export function CategoryListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryListResponse {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(CategoryResponseFromJSON)),
        'total': json['total'],
        'offset': json['offset'],
        'limit': json['limit'],
    };
}

export function CategoryListResponseToJSON(value?: CategoryListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'items': ((value['items'] as Array<any>).map(CategoryResponseToJSON)),
        'total': value['total'],
        'offset': value['offset'],
        'limit': value['limit'],
    };
}

