/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CommentResponse
 */
export interface CommentResponse {
    /**
     *
     * @type {string}
     * @memberof CommentResponse
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof CommentResponse
     */
    authorId: string;
    /**
     *
     * @type {string}
     * @memberof CommentResponse
     */
    authorUsername?: string;
    /**
     *
     * @type {string}
     * @memberof CommentResponse
     */
    content: string;
    /**
     *
     * @type {Date}
     * @memberof CommentResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the CommentResponse interface.
 */
export function instanceOfCommentResponse(value: object): value is CommentResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CommentResponseFromJSON(json: any): CommentResponse {
    return CommentResponseFromJSONTyped(json, false);
}

export function CommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'authorId': json['author_id'],
        'authorUsername': json['author_username'] == null ? undefined : json['author_username'],
        'content': json['content'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function CommentResponseToJSON(value?: CommentResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'author_id': value['authorId'],
        'author_username': value['authorUsername'],
        'content': value['content'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

