/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {CommentResponse} from './CommentResponse';
import {CommentResponseFromJSON, CommentResponseToJSON,} from './CommentResponse';

/**
 * 
 * @export
 * @interface CommentListResponse
 */
export interface CommentListResponse {
    /**
     * 
     * @type {Array<CommentResponse>}
     * @memberof CommentListResponse
     */
    comments: Array<CommentResponse>;
}

/**
 * Check if a given object implements the CommentListResponse interface.
 */
export function instanceOfCommentListResponse(value: object): value is CommentListResponse {
    if (!('comments' in value) || value['comments'] === undefined) return false;
    return true;
}

export function CommentListResponseFromJSON(json: any): CommentListResponse {
    return CommentListResponseFromJSONTyped(json, false);
}

export function CommentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': ((json['comments'] as Array<any>).map(CommentResponseFromJSON)),
    };
}

export function CommentListResponseToJSON(value?: CommentListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comments': ((value['comments'] as Array<any>).map(CommentResponseToJSON)),
    };
}

