/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateCategoryRequest
 */
export interface CreateCategoryRequest {
    /**
     *
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateCategoryRequest interface.
 */
export function instanceOfCreateCategoryRequest(value: object): value is CreateCategoryRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateCategoryRequestFromJSON(json: any): CreateCategoryRequest {
    return CreateCategoryRequestFromJSONTyped(json, false);
}

export function CreateCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCategoryRequest {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
    };
}

export function CreateCategoryRequestToJSON(value?: CreateCategoryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
    };
}

