/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreatedIdResponse
 */
export interface CreatedIdResponse {
    /**
     *
     * @type {string}
     * @memberof CreatedIdResponse
     */
    id: string;
}

/**
 * Check if a given object implements the CreatedIdResponse interface.
 */
export function instanceOfCreatedIdResponse(value: object): value is CreatedIdResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreatedIdResponseFromJSON(json: any): CreatedIdResponse {
    return CreatedIdResponseFromJSONTyped(json, false);
}

export function CreatedIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedIdResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
    };
}

export function CreatedIdResponseToJSON(value?: CreatedIdResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
    };
}

