/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {RolePermissions} from './RolePermissions';
import {RolePermissionsFromJSON, RolePermissionsToJSON,} from './RolePermissions';

/**
 *
 * @export
 * @interface CreateRoleRequest
 */
export interface CreateRoleRequest {
    /**
     *
     * @type {string}
     * @memberof CreateRoleRequest
     */
    name: string;
    /**
     *
     * @type {RolePermissions}
     * @memberof CreateRoleRequest
     */
    permissions: RolePermissions;
}

/**
 * Check if a given object implements the CreateRoleRequest interface.
 */
export function instanceOfCreateRoleRequest(value: object): value is CreateRoleRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function CreateRoleRequestFromJSON(json: any): CreateRoleRequest {
    return CreateRoleRequestFromJSONTyped(json, false);
}

export function CreateRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRoleRequest {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
        'permissions': RolePermissionsFromJSON(json['permissions']),
    };
}

export function CreateRoleRequestToJSON(value?: CreateRoleRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
        'permissions': RolePermissionsToJSON(value['permissions']),
    };
}

