/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectInviteRequest
 */
export interface CreateProjectInviteRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateProjectInviteRequest
     */
    roleId: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateProjectInviteRequest
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof CreateProjectInviteRequest
     */
    maxUses?: number | null;
}

/**
 * Check if a given object implements the CreateProjectInviteRequest interface.
 */
export function instanceOfCreateProjectInviteRequest(value: object): value is CreateProjectInviteRequest {
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    return true;
}

export function CreateProjectInviteRequestFromJSON(json: any): CreateProjectInviteRequest {
    return CreateProjectInviteRequestFromJSONTyped(json, false);
}

export function CreateProjectInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectInviteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'roleId': json['role_id'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'maxUses': json['max_uses'] == null ? undefined : json['max_uses'],
    };
}

export function CreateProjectInviteRequestToJSON(value?: CreateProjectInviteRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role_id': value['roleId'],
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
        'max_uses': value['maxUses'],
    };
}

