/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {ProjectScope} from './ProjectScope';
import {ProjectScopeFromJSON, ProjectScopeToJSON,} from './ProjectScope';

/**
 *
 * @export
 * @interface CreateProjectRequest
 */
export interface CreateProjectRequest {
    /**
     *
     * @type {string}
     * @memberof CreateProjectRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CreateProjectRequest
     */
    description?: string | null;
    /**
     *
     * @type {ProjectScope}
     * @memberof CreateProjectRequest
     */
    scope: ProjectScope;
}

/**
 * Check if a given object implements the CreateProjectRequest interface.
 */
export function instanceOfCreateProjectRequest(value: object): value is CreateProjectRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function CreateProjectRequestFromJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestFromJSONTyped(json, false);
}

export function CreateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectRequest {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'scope': ProjectScopeFromJSON(json['scope']),
    };
}

export function CreateProjectRequestToJSON(value?: CreateProjectRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
        'description': value['description'],
        'scope': ProjectScopeToJSON(value['scope']),
    };
}
