/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {IncidentPriority} from './IncidentPriority';
import {IncidentPriorityFromJSON, IncidentPriorityToJSON,} from './IncidentPriority';

/**
 *
 * @export
 * @interface CreateIncidentRequest
 */
export interface CreateIncidentRequest {
    /**
     *
     * @type {string}
     * @memberof CreateIncidentRequest
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof CreateIncidentRequest
     */
    description: string;
    /**
     *
     * @type {string}
     * @memberof CreateIncidentRequest
     */
    categoryId?: string;
    /**
     *
     * @type {IncidentPriority}
     * @memberof CreateIncidentRequest
     */
    priority?: IncidentPriority;
    /**
     *
     * @type {string}
     * @memberof CreateIncidentRequest
     */
    primaryAssigneeId?: string | null;
}

/**
 * Check if a given object implements the CreateIncidentRequest interface.
 */
export function instanceOfCreateIncidentRequest(value: object): value is CreateIncidentRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateIncidentRequestFromJSON(json: any): CreateIncidentRequest {
    return CreateIncidentRequestFromJSONTyped(json, false);
}

export function CreateIncidentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIncidentRequest {
    if (json == null) {
        return json;
    }
    return {

        'title': json['title'],
        'description': json['description'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'priority': json['priority'] == null ? undefined : IncidentPriorityFromJSON(json['priority']),
        'primaryAssigneeId': json['primaryAssigneeId'] == null ? undefined : json['primaryAssigneeId'],
    };
}

export function CreateIncidentRequestToJSON(value?: CreateIncidentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'title': value['title'],
        'description': value['description'],
        'categoryId': value['categoryId'],
        'priority': IncidentPriorityToJSON(value['priority']),
        'primaryAssigneeId': value['primaryAssigneeId'],
    };
}

