/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateOrgInviteRequest
 */
export interface CreateOrgInviteRequest {
    /**
     *
     * @type {Date}
     * @memberof CreateOrgInviteRequest
     */
    expiresAt?: Date | null;
    /**
     *
     * @type {number}
     * @memberof CreateOrgInviteRequest
     */
    maxUses?: number | null;
}

/**
 * Check if a given object implements the CreateOrgInviteRequest interface.
 */
export function instanceOfCreateOrgInviteRequest(value: object): value is CreateOrgInviteRequest {
    return true;
}

export function CreateOrgInviteRequestFromJSON(json: any): CreateOrgInviteRequest {
    return CreateOrgInviteRequestFromJSONTyped(json, false);
}

export function CreateOrgInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrgInviteRequest {
    if (json == null) {
        return json;
    }
    return {

        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'maxUses': json['max_uses'] == null ? undefined : json['max_uses'],
    };
}

export function CreateOrgInviteRequestToJSON(value?: CreateOrgInviteRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
        'max_uses': value['maxUses'],
    };
}
