/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateOrganizationRequest
 */
export interface CreateOrganizationRequest {
    /**
     *
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CreateOrganizationRequest interface.
 */
export function instanceOfCreateOrganizationRequest(value: object): value is CreateOrganizationRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateOrganizationRequestFromJSON(json: any): CreateOrganizationRequest {
    return CreateOrganizationRequestFromJSONTyped(json, false);
}

export function CreateOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateOrganizationRequestToJSON(value?: CreateOrganizationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
        'description': value['description'],
    };
}
