/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateInviteRequest
 */
export interface CreateInviteRequest {
    /**
     *
     * @type {Date}
     * @memberof CreateInviteRequest
     */
    expiresAt?: Date | null;
    /**
     *
     * @type {number}
     * @memberof CreateInviteRequest
     */
    maxUses?: number | null;
}

/**
 * Check if a given object implements the CreateInviteRequest interface.
 */
export function instanceOfCreateInviteRequest(value: object): value is CreateInviteRequest {
    return true;
}

export function CreateInviteRequestFromJSON(json: any): CreateInviteRequest {
    return CreateInviteRequestFromJSONTyped(json, false);
}

export function CreateInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInviteRequest {
    if (json == null) {
        return json;
    }
    return {

        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'maxUses': json['max_uses'] == null ? undefined : json['max_uses'],
    };
}

export function CreateInviteRequestToJSON(value?: CreateInviteRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
        'max_uses': value['maxUses'],
    };
}
