/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CurrentUserResponse
 */
export interface CurrentUserResponse {
    /**
     * 
     * @type {string}
     * @memberof CurrentUserResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUserResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUserResponse
     */
    organizationId?: string | null;
}

/**
 * Check if a given object implements the CurrentUserResponse interface.
 */
export function instanceOfCurrentUserResponse(value: object): value is CurrentUserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CurrentUserResponseFromJSON(json: any): CurrentUserResponse {
    return CurrentUserResponseFromJSONTyped(json, false);
}

export function CurrentUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
    };
}

export function CurrentUserResponseToJSON(value?: CurrentUserResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'username': value['username'],
        'organizationId': value['organizationId'],
    };
}

