/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface FeedbackRequest
 */
export interface FeedbackRequest {
    /**
     * 
     * @type {string}
     * @memberof FeedbackRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackRequest
     */
    message: string;
}

/**
 * Check if a given object implements the FeedbackRequest interface.
 */
export function instanceOfFeedbackRequest(value: object): value is FeedbackRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function FeedbackRequestFromJSON(json: any): FeedbackRequest {
    return FeedbackRequestFromJSONTyped(json, false);
}

export function FeedbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'message': json['message'],
    };
}

export function FeedbackRequestToJSON(value?: FeedbackRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
        'message': value['message'],
    };
}

