/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface HelperResponse
 */
export interface HelperResponse {
    /**
     *
     * @type {string}
     * @memberof HelperResponse
     */
    userId: string;
    /**
     *
     * @type {Date}
     * @memberof HelperResponse
     */
    addedAt: Date;
}

/**
 * Check if a given object implements the HelperResponse interface.
 */
export function instanceOfHelperResponse(value: object): value is HelperResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('addedAt' in value) || value['addedAt'] === undefined) return false;
    return true;
}

export function HelperResponseFromJSON(json: any): HelperResponse {
    return HelperResponseFromJSONTyped(json, false);
}

export function HelperResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelperResponse {
    if (json == null) {
        return json;
    }
    return {

        'userId': json['user_id'],
        'addedAt': (new Date(json['added_at'])),
    };
}

export function HelperResponseToJSON(value?: HelperResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'user_id': value['userId'],
        'added_at': ((value['addedAt']).toISOString()),
    };
}

