/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {IncidentPriority} from './IncidentPriority';
import {IncidentPriorityFromJSON, IncidentPriorityToJSON,} from './IncidentPriority';
import type {IncidentStatus} from './IncidentStatus';
import {IncidentStatusFromJSON, IncidentStatusToJSON,} from './IncidentStatus';

/**
 *
 * @export
 * @interface IncidentSummary
 */
export interface IncidentSummary {
    /**
     *
     * @type {string}
     * @memberof IncidentSummary
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof IncidentSummary
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof IncidentSummary
     */
    categoryId?: string | null;
    /**
     *
     * @type {IncidentPriority}
     * @memberof IncidentSummary
     */
    priority: IncidentPriority;
    /**
     *
     * @type {IncidentStatus}
     * @memberof IncidentSummary
     */
    status: IncidentStatus;
    /**
     *
     * @type {string}
     * @memberof IncidentSummary
     */
    primaryAssigneeId?: string | null;
    /**
     *
     * @type {Date}
     * @memberof IncidentSummary
     */
    reportDate: Date;
}

/**
 * Check if a given object implements the IncidentSummary interface.
 */
export function instanceOfIncidentSummary(value: object): value is IncidentSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('reportDate' in value) || value['reportDate'] === undefined) return false;
    return true;
}

export function IncidentSummaryFromJSON(json: any): IncidentSummary {
    return IncidentSummaryFromJSONTyped(json, false);
}

export function IncidentSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentSummary {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'title': json['title'],
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'priority': IncidentPriorityFromJSON(json['priority']),
        'status': IncidentStatusFromJSON(json['status']),
        'primaryAssigneeId': json['primary_assignee_id'] == null ? undefined : json['primary_assignee_id'],
        'reportDate': (new Date(json['report_date'])),
    };
}

export function IncidentSummaryToJSON(value?: IncidentSummary | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'title': value['title'],
        'category_id': value['categoryId'],
        'priority': IncidentPriorityToJSON(value['priority']),
        'status': IncidentStatusToJSON(value['status']),
        'primary_assignee_id': value['primaryAssigneeId'],
        'report_date': ((value['reportDate']).toISOString()),
    };
}
