/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {IncidentPriority} from './IncidentPriority';
import {IncidentPriorityFromJSON, IncidentPriorityToJSON,} from './IncidentPriority';
import type {IncidentStatus} from './IncidentStatus';
import {IncidentStatusFromJSON, IncidentStatusToJSON,} from './IncidentStatus';

/**
 * 
 * @export
 * @interface IncidentDetailsResponse
 */
export interface IncidentDetailsResponse {
    /**
     * 
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    categoryId?: string;
    /**
     * 
     * @type {IncidentPriority}
     * @memberof IncidentDetailsResponse
     */
    priority: IncidentPriority;
    /**
     * 
     * @type {IncidentStatus}
     * @memberof IncidentDetailsResponse
     */
    status: IncidentStatus;
    /**
     * 
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    reporterId: string;
    /**
     * 
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    primaryAssigneeId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IncidentDetailsResponse
     */
    reportDate: Date;
}

/**
 * Check if a given object implements the IncidentDetailsResponse interface.
 */
export function instanceOfIncidentDetailsResponse(value: object): value is IncidentDetailsResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('reporterId' in value) || value['reporterId'] === undefined) return false;
    if (!('reportDate' in value) || value['reportDate'] === undefined) return false;
    return true;
}

export function IncidentDetailsResponseFromJSON(json: any): IncidentDetailsResponse {
    return IncidentDetailsResponseFromJSONTyped(json, false);
}

export function IncidentDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentDetailsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['projectId'],
        'title': json['title'],
        'description': json['description'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'priority': IncidentPriorityFromJSON(json['priority']),
        'status': IncidentStatusFromJSON(json['status']),
        'reporterId': json['reporterId'],
        'primaryAssigneeId': json['primaryAssigneeId'] == null ? undefined : json['primaryAssigneeId'],
        'reportDate': (new Date(json['reportDate'])),
    };
}

export function IncidentDetailsResponseToJSON(value?: IncidentDetailsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'title': value['title'],
        'description': value['description'],
        'categoryId': value['categoryId'],
        'priority': IncidentPriorityToJSON(value['priority']),
        'status': IncidentStatusToJSON(value['status']),
        'reporterId': value['reporterId'],
        'primaryAssigneeId': value['primaryAssigneeId'],
        'reportDate': ((value['reportDate']).toISOString()),
    };
}

