/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const IncidentLogType = {
    Comment: 'COMMENT',
    StatusChanged: 'STATUS_CHANGED',
    AssigneeChanged: 'ASSIGNEE_CHANGED',
    HelperAdded: 'HELPER_ADDED',
    HelperRemoved: 'HELPER_REMOVED',
    PriorityChanged: 'PRIORITY_CHANGED',
    CategoryChanged: 'CATEGORY_CHANGED',
    Created: 'CREATED',
    Closed: 'CLOSED'
} as const;
export type IncidentLogType = typeof IncidentLogType[keyof typeof IncidentLogType];


export function instanceOfIncidentLogType(value: any): boolean {
    for (const key in IncidentLogType) {
        if (Object.prototype.hasOwnProperty.call(IncidentLogType, key)) {
            if ((IncidentLogType as Record<string, IncidentLogType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IncidentLogTypeFromJSON(json: any): IncidentLogType {
    return IncidentLogTypeFromJSONTyped(json, false);
}

export function IncidentLogTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentLogType {
    return json as IncidentLogType;
}

export function IncidentLogTypeToJSON(value?: IncidentLogType | null): any {
    return value as any;
}
