/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {IncidentPriority} from './IncidentPriority';
import {IncidentPriorityFromJSON, IncidentPriorityToJSON,} from './IncidentPriority';
import type {IncidentStatus} from './IncidentStatus';
import {IncidentStatusFromJSON, IncidentStatusToJSON,} from './IncidentStatus';
import type {HelperResponse} from './HelperResponse';
import {HelperResponseFromJSON, HelperResponseToJSON,} from './HelperResponse';

/**
 *
 * @export
 * @interface IncidentDetailsResponse
 */
export interface IncidentDetailsResponse {
    /**
     *
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    projectId: string;
    /**
     *
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    description: string;
    /**
     *
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    categoryId?: string | null;
    /**
     *
     * @type {IncidentPriority}
     * @memberof IncidentDetailsResponse
     */
    priority: IncidentPriority;
    /**
     *
     * @type {IncidentStatus}
     * @memberof IncidentDetailsResponse
     */
    status: IncidentStatus;
    /**
     *
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    reporterId: string;
    /**
     *
     * @type {string}
     * @memberof IncidentDetailsResponse
     */
    primaryAssigneeId?: string | null;
    /**
     *
     * @type {Date}
     * @memberof IncidentDetailsResponse
     */
    reportDate: Date;
    /**
     *
     * @type {Date}
     * @memberof IncidentDetailsResponse
     */
    closingDate?: Date | null;
    /**
     *
     * @type {Array<HelperResponse>}
     * @memberof IncidentDetailsResponse
     */
    helpers: Array<HelperResponse>;
}

/**
 * Check if a given object implements the IncidentDetailsResponse interface.
 */
export function instanceOfIncidentDetailsResponse(value: object): value is IncidentDetailsResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('reporterId' in value) || value['reporterId'] === undefined) return false;
    if (!('reportDate' in value) || value['reportDate'] === undefined) return false;
    if (!('helpers' in value) || value['helpers'] === undefined) return false;
    return true;
}

export function IncidentDetailsResponseFromJSON(json: any): IncidentDetailsResponse {
    return IncidentDetailsResponseFromJSONTyped(json, false);
}

export function IncidentDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentDetailsResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'projectId': json['project_id'],
        'title': json['title'],
        'description': json['description'],
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'priority': IncidentPriorityFromJSON(json['priority']),
        'status': IncidentStatusFromJSON(json['status']),
        'reporterId': json['reporter_id'],
        'primaryAssigneeId': json['primary_assignee_id'] == null ? undefined : json['primary_assignee_id'],
        'reportDate': (new Date(json['report_date'])),
        'closingDate': json['closing_date'] == null ? undefined : (new Date(json['closing_date'])),
        'helpers': ((json['helpers'] as Array<any>).map(HelperResponseFromJSON)),
    };
}

export function IncidentDetailsResponseToJSON(value?: IncidentDetailsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'project_id': value['projectId'],
        'title': value['title'],
        'description': value['description'],
        'category_id': value['categoryId'],
        'priority': IncidentPriorityToJSON(value['priority']),
        'status': IncidentStatusToJSON(value['status']),
        'reporter_id': value['reporterId'],
        'primary_assignee_id': value['primaryAssigneeId'],
        'report_date': ((value['reportDate']).toISOString()),
        'closing_date': value['closingDate'] == null ? undefined : ((value['closingDate'] as any).toISOString()),
        'helpers': ((value['helpers'] as Array<any>).map(HelperResponseToJSON)),
    };
}

