/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {IncidentSummary} from './IncidentSummary';
import {IncidentSummaryFromJSON, IncidentSummaryToJSON,} from './IncidentSummary';

/**
 *
 * @export
 * @interface IncidentListResponse
 */
export interface IncidentListResponse {
    /**
     *
     * @type {Array<IncidentSummary>}
     * @memberof IncidentListResponse
     */
    items: Array<IncidentSummary>;
    /**
     *
     * @type {number}
     * @memberof IncidentListResponse
     */
    total: number;
    /**
     *
     * @type {number}
     * @memberof IncidentListResponse
     */
    offset: number;
    /**
     *
     * @type {number}
     * @memberof IncidentListResponse
     */
    limit: number;
}

/**
 * Check if a given object implements the IncidentListResponse interface.
 */
export function instanceOfIncidentListResponse(value: object): value is IncidentListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function IncidentListResponseFromJSON(json: any): IncidentListResponse {
    return IncidentListResponseFromJSONTyped(json, false);
}

export function IncidentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentListResponse {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(IncidentSummaryFromJSON)),
        'total': json['total'],
        'offset': json['offset'],
        'limit': json['limit'],
    };
}

export function IncidentListResponseToJSON(value?: IncidentListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'items': ((value['items'] as Array<any>).map(IncidentSummaryToJSON)),
        'total': value['total'],
        'offset': value['offset'],
        'limit': value['limit'],
    };
}

