/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const IncidentStatus = {
    New: 'NEW',
    ProblemIsBeingSolved: 'PROBLEM_IS_BEING_SOLVED',
    Resolved: 'RESOLVED',
    Closed: 'CLOSED',
    Rejected: 'REJECTED'
} as const;
export type IncidentStatus = typeof IncidentStatus[keyof typeof IncidentStatus];


export function instanceOfIncidentStatus(value: any): boolean {
    for (const key in IncidentStatus) {
        if (Object.prototype.hasOwnProperty.call(IncidentStatus, key)) {
            if ((IncidentStatus as Record<string, IncidentStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IncidentStatusFromJSON(json: any): IncidentStatus {
    return IncidentStatusFromJSONTyped(json, false);
}

export function IncidentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentStatus {
    return json as IncidentStatus;
}

export function IncidentStatusToJSON(value?: IncidentStatus | null): any {
    return value as any;
}

