/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {IncidentLogType} from './IncidentLogType';
import {IncidentLogTypeFromJSON, IncidentLogTypeToJSON,} from './IncidentLogType';

/**
 *
 * @export
 * @interface IncidentLogEntry
 */
export interface IncidentLogEntry {
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    incidentId: string;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    actorId: string;
    /**
     *
     * @type {IncidentLogType}
     * @memberof IncidentLogEntry
     */
    type: IncidentLogType;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    comment?: string | null;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    oldValue?: string | null;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    newValue?: string | null;
    /**
     *
     * @type {Date}
     * @memberof IncidentLogEntry
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the IncidentLogEntry interface.
 */
export function instanceOfIncidentLogEntry(value: object): value is IncidentLogEntry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('incidentId' in value) || value['incidentId'] === undefined) return false;
    if (!('actorId' in value) || value['actorId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function IncidentLogEntryFromJSON(json: any): IncidentLogEntry {
    return IncidentLogEntryFromJSONTyped(json, false);
}

export function IncidentLogEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentLogEntry {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'incidentId': json['incident_id'],
        'actorId': json['actor_id'],
        'type': IncidentLogTypeFromJSON(json['type']),
        'comment': json['comment'] == null ? undefined : json['comment'],
        'oldValue': json['old_value'] == null ? undefined : json['old_value'],
        'newValue': json['new_value'] == null ? undefined : json['new_value'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function IncidentLogEntryToJSON(value?: IncidentLogEntry | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'incident_id': value['incidentId'],
        'actor_id': value['actorId'],
        'type': IncidentLogTypeToJSON(value['type']),
        'comment': value['comment'],
        'old_value': value['oldValue'],
        'new_value': value['newValue'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

