/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface IncidentLogEntry
 */
export interface IncidentLogEntry {
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    incidentId: string;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    type: IncidentLogEntryTypeEnum;
    /**
     *
     * @type {Date}
     * @memberof IncidentLogEntry
     */
    createdAt: Date;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    actorId: string;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    comment?: string | null;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    oldValue?: string | null;
    /**
     *
     * @type {string}
     * @memberof IncidentLogEntry
     */
    newValue?: string | null;
}


/**
 * @export
 */
export const IncidentLogEntryTypeEnum = {
    Comment: 'COMMENT',
    StatusChanged: 'STATUS_CHANGED',
    AssigneeChanged: 'ASSIGNEE_CHANGED',
    HelperAdded: 'HELPER_ADDED',
    HelperRemoved: 'HELPER_REMOVED',
    PriorityChanged: 'PRIORITY_CHANGED',
    CategoryChanged: 'CATEGORY_CHANGED',
    Created: 'CREATED',
    Closed: 'CLOSED'
} as const;
export type IncidentLogEntryTypeEnum = typeof IncidentLogEntryTypeEnum[keyof typeof IncidentLogEntryTypeEnum];


/**
 * Check if a given object implements the IncidentLogEntry interface.
 */
export function instanceOfIncidentLogEntry(value: object): value is IncidentLogEntry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('incidentId' in value) || value['incidentId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('actorId' in value) || value['actorId'] === undefined) return false;
    return true;
}

export function IncidentLogEntryFromJSON(json: any): IncidentLogEntry {
    return IncidentLogEntryFromJSONTyped(json, false);
}

export function IncidentLogEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentLogEntry {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'incidentId': json['incident_id'],
        'type': json['type'],
        'createdAt': (new Date(json['created_at'])),
        'actorId': json['actor_id'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'oldValue': json['old_value'] == null ? undefined : json['old_value'],
        'newValue': json['new_value'] == null ? undefined : json['new_value'],
    };
}

export function IncidentLogEntryToJSON(value?: IncidentLogEntry | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'incident_id': value['incidentId'],
        'type': value['type'],
        'created_at': ((value['createdAt']).toISOString()),
        'actor_id': value['actorId'],
        'comment': value['comment'],
        'old_value': value['oldValue'],
        'new_value': value['newValue'],
    };
}

