/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {IncidentLogEntry} from './IncidentLogEntry';
import {IncidentLogEntryFromJSON, IncidentLogEntryToJSON,} from './IncidentLogEntry';

/**
 *
 * @export
 * @interface IncidentLogListResponse
 */
export interface IncidentLogListResponse {
    /**
     *
     * @type {Array<IncidentLogEntry>}
     * @memberof IncidentLogListResponse
     */
    items: Array<IncidentLogEntry>;
    /**
     *
     * @type {number}
     * @memberof IncidentLogListResponse
     */
    total: number;
    /**
     *
     * @type {number}
     * @memberof IncidentLogListResponse
     */
    offset: number;
    /**
     *
     * @type {number}
     * @memberof IncidentLogListResponse
     */
    limit: number;
}

/**
 * Check if a given object implements the IncidentLogListResponse interface.
 */
export function instanceOfIncidentLogListResponse(value: object): value is IncidentLogListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function IncidentLogListResponseFromJSON(json: any): IncidentLogListResponse {
    return IncidentLogListResponseFromJSONTyped(json, false);
}

export function IncidentLogListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentLogListResponse {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(IncidentLogEntryFromJSON)),
        'total': json['total'],
        'offset': json['offset'],
        'limit': json['limit'],
    };
}

export function IncidentLogListResponseToJSON(value?: IncidentLogListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'items': ((value['items'] as Array<any>).map(IncidentLogEntryToJSON)),
        'total': value['total'],
        'offset': value['offset'],
        'limit': value['limit'],
    };
}

