/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const IncidentPriority = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;
export type IncidentPriority = typeof IncidentPriority[keyof typeof IncidentPriority];


export function instanceOfIncidentPriority(value: any): boolean {
    for (const key in IncidentPriority) {
        if (Object.prototype.hasOwnProperty.call(IncidentPriority, key)) {
            if ((IncidentPriority as Record<string, IncidentPriority>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IncidentPriorityFromJSON(json: any): IncidentPriority {
    return IncidentPriorityFromJSONTyped(json, false);
}

export function IncidentPriorityFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentPriority {
    return json as IncidentPriority;
}

export function IncidentPriorityToJSON(value?: IncidentPriority | null): any {
    return value as any;
}

