/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {InviteScope} from './InviteScope';
import {InviteScopeFromJSON, InviteScopeToJSON,} from './InviteScope';

/**
 *
 * @export
 * @interface InvitePreviewResponse
 */
export interface InvitePreviewResponse {
    /**
     *
     * @type {InviteScope}
     * @memberof InvitePreviewResponse
     */
    scope: InviteScope;
    /**
     *
     * @type {string}
     * @memberof InvitePreviewResponse
     */
    targetName: string;
    /**
     *
     * @type {boolean}
     * @memberof InvitePreviewResponse
     */
    isValid: boolean;
    /**
     *
     * @type {Date}
     * @memberof InvitePreviewResponse
     */
    expiresAt?: Date | null;
}

/**
 * Check if a given object implements the InvitePreviewResponse interface.
 */
export function instanceOfInvitePreviewResponse(value: object): value is InvitePreviewResponse {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('targetName' in value) || value['targetName'] === undefined) return false;
    if (!('isValid' in value) || value['isValid'] === undefined) return false;
    return true;
}

export function InvitePreviewResponseFromJSON(json: any): InvitePreviewResponse {
    return InvitePreviewResponseFromJSONTyped(json, false);
}

export function InvitePreviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitePreviewResponse {
    if (json == null) {
        return json;
    }
    return {

        'scope': InviteScopeFromJSON(json['scope']),
        'targetName': json['target_name'],
        'isValid': json['is_valid'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
    };
}

export function InvitePreviewResponseToJSON(value?: InvitePreviewResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'scope': InviteScopeToJSON(value['scope']),
        'target_name': value['targetName'],
        'is_valid': value['isValid'],
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
    };
}

