/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const InviteScope = {
    Organization: 'ORGANIZATION',
    Project: 'PROJECT'
} as const;
export type InviteScope = typeof InviteScope[keyof typeof InviteScope];


export function instanceOfInviteScope(value: any): boolean {
    for (const key in InviteScope) {
        if (Object.prototype.hasOwnProperty.call(InviteScope, key)) {
            if ((InviteScope as Record<string, InviteScope>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InviteScopeFromJSON(json: any): InviteScope {
    return InviteScopeFromJSONTyped(json, false);
}

export function InviteScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteScope {
    return json as InviteScope;
}

export function InviteScopeToJSON(value?: InviteScope | null): any {
    return value as any;
}

