/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InviteResponse
 */
export interface InviteResponse {
    /**
     *
     * @type {string}
     * @memberof InviteResponse
     */
    token: string;
    /**
     *
     * @type {string}
     * @memberof InviteResponse
     */
    inviteUrl?: string | null;
}

/**
 * Check if a given object implements the InviteResponse interface.
 */
export function instanceOfInviteResponse(value: object): value is InviteResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function InviteResponseFromJSON(json: any): InviteResponse {
    return InviteResponseFromJSONTyped(json, false);
}

export function InviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteResponse {
    if (json == null) {
        return json;
    }
    return {

        'token': json['token'],
        'inviteUrl': json['inviteUrl'] == null ? undefined : json['inviteUrl'],
    };
}

export function InviteResponseToJSON(value?: InviteResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'token': value['token'],
        'inviteUrl': value['inviteUrl'],
    };
}

