/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface InvitePreviewResponse
 */
export interface InvitePreviewResponse {
    /**
     * 
     * @type {string}
     * @memberof InvitePreviewResponse
     */
    scope: InvitePreviewResponseScopeEnum;
    /**
     * 
     * @type {string}
     * @memberof InvitePreviewResponse
     */
    targetName: string;
    /**
     * 
     * @type {boolean}
     * @memberof InvitePreviewResponse
     */
    isValid: boolean;
    /**
     * 
     * @type {Date}
     * @memberof InvitePreviewResponse
     */
    expiresAt?: Date | null;
}


/**
 * @export
 */
export const InvitePreviewResponseScopeEnum = {
    Organization: 'ORGANIZATION',
    Project: 'PROJECT'
} as const;
export type InvitePreviewResponseScopeEnum = typeof InvitePreviewResponseScopeEnum[keyof typeof InvitePreviewResponseScopeEnum];


/**
 * Check if a given object implements the InvitePreviewResponse interface.
 */
export function instanceOfInvitePreviewResponse(value: object): value is InvitePreviewResponse {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('targetName' in value) || value['targetName'] === undefined) return false;
    if (!('isValid' in value) || value['isValid'] === undefined) return false;
    return true;
}

export function InvitePreviewResponseFromJSON(json: any): InvitePreviewResponse {
    return InvitePreviewResponseFromJSONTyped(json, false);
}

export function InvitePreviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitePreviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'],
        'targetName': json['targetName'],
        'isValid': json['isValid'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
    };
}

export function InvitePreviewResponseToJSON(value?: InvitePreviewResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'scope': value['scope'],
        'targetName': value['targetName'],
        'isValid': value['isValid'],
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
    };
}

