/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface JoinByInviteRequest
 */
export interface JoinByInviteRequest {
    /**
     *
     * @type {string}
     * @memberof JoinByInviteRequest
     */
    token: string;
}

/**
 * Check if a given object implements the JoinByInviteRequest interface.
 */
export function instanceOfJoinByInviteRequest(value: object): value is JoinByInviteRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function JoinByInviteRequestFromJSON(json: any): JoinByInviteRequest {
    return JoinByInviteRequestFromJSONTyped(json, false);
}

export function JoinByInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinByInviteRequest {
    if (json == null) {
        return json;
    }
    return {

        'token': json['token'],
    };
}

export function JoinByInviteRequestToJSON(value?: JoinByInviteRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'token': value['token'],
    };
}

