/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {CurrentUserResponse} from './CurrentUserResponse';
import {CurrentUserResponseFromJSON, CurrentUserResponseToJSON,} from './CurrentUserResponse';

/**
 *
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     *
     * @type {string}
     * @memberof LoginResponse
     */
    accessToken: string;
    /**
     *
     * @type {string}
     * @memberof LoginResponse
     */
    tokenType: string;
    /**
     *
     * @type {CurrentUserResponse}
     * @memberof LoginResponse
     */
    user: CurrentUserResponse;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if (json == null) {
        return json;
    }
    return {

        'accessToken': json['access_token'],
        'tokenType': json['token_type'],
        'user': CurrentUserResponseFromJSON(json['user']),
    };
}

export function LoginResponseToJSON(value?: LoginResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'user': CurrentUserResponseToJSON(value['user']),
    };
}

