/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizationResponse
 */
export interface OrganizationResponse {
    /**
     *
     * @type {string}
     * @memberof OrganizationResponse
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof OrganizationResponse
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof OrganizationResponse
     */
    description?: string | null;
}

/**
 * Check if a given object implements the OrganizationResponse interface.
 */
export function instanceOfOrganizationResponse(value: object): value is OrganizationResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganizationResponseFromJSON(json: any): OrganizationResponse {
    return OrganizationResponseFromJSONTyped(json, false);
}

export function OrganizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function OrganizationResponseToJSON(value?: OrganizationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

