/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PasswordResetRequest
 */
export interface PasswordResetRequest {
    /**
     *
     * @type {string}
     * @memberof PasswordResetRequest
     */
    emailOrUsername: string;
}

/**
 * Check if a given object implements the PasswordResetRequest interface.
 */
export function instanceOfPasswordResetRequest(value: object): value is PasswordResetRequest {
    if (!('emailOrUsername' in value) || value['emailOrUsername'] === undefined) return false;
    return true;
}

export function PasswordResetRequestFromJSON(json: any): PasswordResetRequest {
    return PasswordResetRequestFromJSONTyped(json, false);
}

export function PasswordResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetRequest {
    if (json == null) {
        return json;
    }
    return {

        'emailOrUsername': json['email_or_username'],
    };
}

export function PasswordResetRequestToJSON(value?: PasswordResetRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'email_or_username': value['emailOrUsername'],
    };
}

