/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PasswordResetConfirmRequest
 */
export interface PasswordResetConfirmRequest {
    /**
     *
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    resetToken: string;
    /**
     *
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the PasswordResetConfirmRequest interface.
 */
export function instanceOfPasswordResetConfirmRequest(value: object): value is PasswordResetConfirmRequest {
    if (!('resetToken' in value) || value['resetToken'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function PasswordResetConfirmRequestFromJSON(json: any): PasswordResetConfirmRequest {
    return PasswordResetConfirmRequestFromJSONTyped(json, false);
}

export function PasswordResetConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetConfirmRequest {
    if (json == null) {
        return json;
    }
    return {

        'resetToken': json['resetToken'],
        'newPassword': json['newPassword'],
    };
}

export function PasswordResetConfirmRequestToJSON(value?: PasswordResetConfirmRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'resetToken': value['resetToken'],
        'newPassword': value['newPassword'],
    };
}

