/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProfileResponse
 */
export interface ProfileResponse {
    /**
     *
     * @type {string}
     * @memberof ProfileResponse
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ProfileResponse
     */
    username: string;
    /**
     *
     * @type {string}
     * @memberof ProfileResponse
     */
    bio?: string | null;
    /**
     *
     * @type {string}
     * @memberof ProfileResponse
     */
    profilePictureUrl?: string | null;
}

/**
 * Check if a given object implements the ProfileResponse interface.
 */
export function instanceOfProfileResponse(value: object): value is ProfileResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function ProfileResponseFromJSON(json: any): ProfileResponse {
    return ProfileResponseFromJSONTyped(json, false);
}

export function ProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'username': json['username'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'profilePictureUrl': json['profile_picture_url'] == null ? undefined : json['profile_picture_url'],
    };
}

export function ProfileResponseToJSON(value?: ProfileResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'username': value['username'],
        'bio': value['bio'],
        'profile_picture_url': value['profilePictureUrl'],
    };
}

