/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {ProjectScope} from './ProjectScope';
import {ProjectScopeFromJSON, ProjectScopeToJSON,} from './ProjectScope';

/**
 *
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     *
     * @type {string}
     * @memberof ProjectResponse
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponse
     */
    organizationId?: string | null;
    /**
     *
     * @type {string}
     * @memberof ProjectResponse
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponse
     */
    description?: string | null;
    /**
     *
     * @type {ProjectScope}
     * @memberof ProjectResponse
     */
    scope: ProjectScope;
}

/**
 * Check if a given object implements the ProjectResponse interface.
 */
export function instanceOfProjectResponse(value: object): value is ProjectResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function ProjectResponseFromJSON(json: any): ProjectResponse {
    return ProjectResponseFromJSONTyped(json, false);
}

export function ProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'scope': ProjectScopeFromJSON(json['scope']),
    };
}

export function ProjectResponseToJSON(value?: ProjectResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'organization_id': value['organizationId'],
        'name': value['name'],
        'description': value['description'],
        'scope': ProjectScopeToJSON(value['scope']),
    };
}
