/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProjectMemberResponse
 */
export interface ProjectMemberResponse {
    /**
     *
     * @type {string}
     * @memberof ProjectMemberResponse
     */
    userId: string;
    /**
     *
     * @type {string}
     * @memberof ProjectMemberResponse
     */
    username: string;
    /**
     *
     * @type {string}
     * @memberof ProjectMemberResponse
     */
    roleId: string;
    /**
     *
     * @type {string}
     * @memberof ProjectMemberResponse
     */
    roleName: string;
}

/**
 * Check if a given object implements the ProjectMemberResponse interface.
 */
export function instanceOfProjectMemberResponse(value: object): value is ProjectMemberResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('roleName' in value) || value['roleName'] === undefined) return false;
    return true;
}

export function ProjectMemberResponseFromJSON(json: any): ProjectMemberResponse {
    return ProjectMemberResponseFromJSONTyped(json, false);
}

export function ProjectMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectMemberResponse {
    if (json == null) {
        return json;
    }
    return {

        'userId': json['userId'],
        'username': json['username'],
        'roleId': json['roleId'],
        'roleName': json['roleName'],
    };
}

export function ProjectMemberResponseToJSON(value?: ProjectMemberResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'userId': value['userId'],
        'username': value['username'],
        'roleId': value['roleId'],
        'roleName': value['roleName'],
    };
}

