/* tslint:disable */
/* eslint-disable */

/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     *
     * @type {string}
     * @memberof ProjectResponse
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponse
     */
    organizationId?: string | null;
    /**
     *
     * @type {string}
     * @memberof ProjectResponse
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponse
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof ProjectResponse
     */
    scope: ProjectResponseScopeEnum;
}


/**
 * @export
 */
export const ProjectResponseScopeEnum = {
    Private: 'PRIVATE',
    Organization: 'ORGANIZATION'
} as const;
export type ProjectResponseScopeEnum = typeof ProjectResponseScopeEnum[keyof typeof ProjectResponseScopeEnum];


/**
 * Check if a given object implements the ProjectResponse interface.
 */
export function instanceOfProjectResponse(value: object): value is ProjectResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function ProjectResponseFromJSON(json: any): ProjectResponse {
    return ProjectResponseFromJSONTyped(json, false);
}

export function ProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'scope': json['scope'],
    };
}

export function ProjectResponseToJSON(value?: ProjectResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'organization_id': value['organizationId'],
        'name': value['name'],
        'description': value['description'],
        'scope': value['scope'],
    };
}

