/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {ProjectResponse} from './ProjectResponse';
import {ProjectResponseFromJSON, ProjectResponseToJSON,} from './ProjectResponse';

/**
 *
 * @export
 * @interface ProjectListResponse
 */
export interface ProjectListResponse {
    /**
     *
     * @type {Array<ProjectResponse>}
     * @memberof ProjectListResponse
     */
    items: Array<ProjectResponse>;
    /**
     *
     * @type {number}
     * @memberof ProjectListResponse
     */
    total: number;
    /**
     *
     * @type {number}
     * @memberof ProjectListResponse
     */
    offset: number;
    /**
     *
     * @type {number}
     * @memberof ProjectListResponse
     */
    limit: number;
}

/**
 * Check if a given object implements the ProjectListResponse interface.
 */
export function instanceOfProjectListResponse(value: object): value is ProjectListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ProjectListResponseFromJSON(json: any): ProjectListResponse {
    return ProjectListResponseFromJSONTyped(json, false);
}

export function ProjectListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectListResponse {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(ProjectResponseFromJSON)),
        'total': json['total'],
        'offset': json['offset'],
        'limit': json['limit'],
    };
}

export function ProjectListResponseToJSON(value?: ProjectListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'items': ((value['items'] as Array<any>).map(ProjectResponseToJSON)),
        'total': value['total'],
        'offset': value['offset'],
        'limit': value['limit'],
    };
}

