/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const ProjectScope = {
    Private: 'PRIVATE',
    Organization: 'ORGANIZATION'
} as const;
export type ProjectScope = typeof ProjectScope[keyof typeof ProjectScope];


export function instanceOfProjectScope(value: any): boolean {
    for (const key in ProjectScope) {
        if (Object.prototype.hasOwnProperty.call(ProjectScope, key)) {
            if ((ProjectScope as Record<string, ProjectScope>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProjectScopeFromJSON(json: any): ProjectScope {
    return ProjectScopeFromJSONTyped(json, false);
}

export function ProjectScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectScope {
    return json as ProjectScope;
}

export function ProjectScopeToJSON(value?: ProjectScope | null): any {
    return value as any;
}

