/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {ProjectMemberResponse} from './ProjectMemberResponse';
import {ProjectMemberResponseFromJSON, ProjectMemberResponseToJSON,} from './ProjectMemberResponse';

/**
 *
 * @export
 * @interface ProjectMemberListResponse
 */
export interface ProjectMemberListResponse {
    /**
     *
     * @type {Array<ProjectMemberResponse>}
     * @memberof ProjectMemberListResponse
     */
    members: Array<ProjectMemberResponse>;
}

/**
 * Check if a given object implements the ProjectMemberListResponse interface.
 */
export function instanceOfProjectMemberListResponse(value: object): value is ProjectMemberListResponse {
    if (!('members' in value) || value['members'] === undefined) return false;
    return true;
}

export function ProjectMemberListResponseFromJSON(json: any): ProjectMemberListResponse {
    return ProjectMemberListResponseFromJSONTyped(json, false);
}

export function ProjectMemberListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectMemberListResponse {
    if (json == null) {
        return json;
    }
    return {

        'members': ((json['members'] as Array<any>).map(ProjectMemberResponseFromJSON)),
    };
}

export function ProjectMemberListResponseToJSON(value?: ProjectMemberListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'members': ((value['members'] as Array<any>).map(ProjectMemberResponseToJSON)),
    };
}

