/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RefreshResponse
 */
export interface RefreshResponse {
    /**
     *
     * @type {string}
     * @memberof RefreshResponse
     */
    accessToken: string;
    /**
     *
     * @type {string}
     * @memberof RefreshResponse
     */
    tokenType: string;
    /**
     * Lifetime of the access token in seconds.
     * @type {number}
     * @memberof RefreshResponse
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the RefreshResponse interface.
 */
export function instanceOfRefreshResponse(value: object): value is RefreshResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function RefreshResponseFromJSON(json: any): RefreshResponse {
    return RefreshResponseFromJSONTyped(json, false);
}

export function RefreshResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshResponse {
    if (json == null) {
        return json;
    }
    return {

        'accessToken': json['access_token'],
        'tokenType': json['token_type'],
        'expiresIn': json['expires_in'],
    };
}

export function RefreshResponseToJSON(value?: RefreshResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
    };
}
