/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {RoleResponse} from './RoleResponse';
import {RoleResponseFromJSON, RoleResponseToJSON,} from './RoleResponse';

/**
 *
 * @export
 * @interface RoleListResponse
 */
export interface RoleListResponse {
    /**
     *
     * @type {Array<RoleResponse>}
     * @memberof RoleListResponse
     */
    items: Array<RoleResponse>;
    /**
     *
     * @type {number}
     * @memberof RoleListResponse
     */
    total: number;
    /**
     *
     * @type {number}
     * @memberof RoleListResponse
     */
    offset: number;
    /**
     *
     * @type {number}
     * @memberof RoleListResponse
     */
    limit: number;
}

/**
 * Check if a given object implements the RoleListResponse interface.
 */
export function instanceOfRoleListResponse(value: object): value is RoleListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function RoleListResponseFromJSON(json: any): RoleListResponse {
    return RoleListResponseFromJSONTyped(json, false);
}

export function RoleListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleListResponse {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(RoleResponseFromJSON)),
        'total': json['total'],
        'offset': json['offset'],
        'limit': json['limit'],
    };
}

export function RoleListResponseToJSON(value?: RoleListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'items': ((value['items'] as Array<any>).map(RoleResponseToJSON)),
        'total': value['total'],
        'offset': value['offset'],
        'limit': value['limit'],
    };
}

