/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RolePermissions
 */
export interface RolePermissions {
    /**
     *
     * @type {boolean}
     * @memberof RolePermissions
     */
    canWriteTickets: boolean;
    /**
     *
     * @type {boolean}
     * @memberof RolePermissions
     */
    canHelp: boolean;
    /**
     *
     * @type {boolean}
     * @memberof RolePermissions
     */
    canAssignHelp: boolean;
    /**
     *
     * @type {boolean}
     * @memberof RolePermissions
     */
    canChangeStatus: boolean;
    /**
     *
     * @type {boolean}
     * @memberof RolePermissions
     */
    canMakeRoles: boolean;
    /**
     *
     * @type {boolean}
     * @memberof RolePermissions
     */
    canChangeRoles: boolean;
    /**
     *
     * @type {boolean}
     * @memberof RolePermissions
     */
    canAssignPeopleToProject: boolean;
}

/**
 * Check if a given object implements the RolePermissions interface.
 */
export function instanceOfRolePermissions(value: object): value is RolePermissions {
    if (!('canWriteTickets' in value) || value['canWriteTickets'] === undefined) return false;
    if (!('canHelp' in value) || value['canHelp'] === undefined) return false;
    if (!('canAssignHelp' in value) || value['canAssignHelp'] === undefined) return false;
    if (!('canChangeStatus' in value) || value['canChangeStatus'] === undefined) return false;
    if (!('canMakeRoles' in value) || value['canMakeRoles'] === undefined) return false;
    if (!('canChangeRoles' in value) || value['canChangeRoles'] === undefined) return false;
    if (!('canAssignPeopleToProject' in value) || value['canAssignPeopleToProject'] === undefined) return false;
    return true;
}

export function RolePermissionsFromJSON(json: any): RolePermissions {
    return RolePermissionsFromJSONTyped(json, false);
}

export function RolePermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RolePermissions {
    if (json == null) {
        return json;
    }
    return {

        'canWriteTickets': json['can_write_tickets'],
        'canHelp': json['can_help'],
        'canAssignHelp': json['can_assign_help'],
        'canChangeStatus': json['can_change_status'],
        'canMakeRoles': json['can_make_roles'],
        'canChangeRoles': json['can_change_roles'],
        'canAssignPeopleToProject': json['can_assign_people_to_project'],
    };
}

export function RolePermissionsToJSON(value?: RolePermissions | null): any {
    if (value == null) {
        return value;
    }
    return {

        'can_write_tickets': value['canWriteTickets'],
        'can_help': value['canHelp'],
        'can_assign_help': value['canAssignHelp'],
        'can_change_status': value['canChangeStatus'],
        'can_make_roles': value['canMakeRoles'],
        'can_change_roles': value['canChangeRoles'],
        'can_assign_people_to_project': value['canAssignPeopleToProject'],
    };
}

