/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateIncidentAssigneeRequest
 */
export interface UpdateIncidentAssigneeRequest {
    /**
     *
     * @type {string}
     * @memberof UpdateIncidentAssigneeRequest
     */
    primaryAssigneeId?: string | null;
}

/**
 * Check if a given object implements the UpdateIncidentAssigneeRequest interface.
 */
export function instanceOfUpdateIncidentAssigneeRequest(value: object): value is UpdateIncidentAssigneeRequest {
    return true;
}

export function UpdateIncidentAssigneeRequestFromJSON(json: any): UpdateIncidentAssigneeRequest {
    return UpdateIncidentAssigneeRequestFromJSONTyped(json, false);
}

export function UpdateIncidentAssigneeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIncidentAssigneeRequest {
    if (json == null) {
        return json;
    }
    return {

        'primaryAssigneeId': json['primary_assignee_id'] == null ? undefined : json['primary_assignee_id'],
    };
}

export function UpdateIncidentAssigneeRequestToJSON(value?: UpdateIncidentAssigneeRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'primary_assignee_id': value['primaryAssigneeId'],
    };
}

