/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {RolePermissions} from './RolePermissions';
import {RolePermissionsFromJSON, RolePermissionsToJSON,} from './RolePermissions';

/**
 *
 * @export
 * @interface UpdateRoleRequest
 */
export interface UpdateRoleRequest {
    /**
     *
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    name?: string;
    /**
     *
     * @type {RolePermissions}
     * @memberof UpdateRoleRequest
     */
    permissions?: RolePermissions;
}

/**
 * Check if a given object implements the UpdateRoleRequest interface.
 */
export function instanceOfUpdateRoleRequest(value: object): value is UpdateRoleRequest {
    return true;
}

export function UpdateRoleRequestFromJSON(json: any): UpdateRoleRequest {
    return UpdateRoleRequestFromJSONTyped(json, false);
}

export function UpdateRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRoleRequest {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'] == null ? undefined : json['name'],
        'permissions': json['permissions'] == null ? undefined : RolePermissionsFromJSON(json['permissions']),
    };
}

export function UpdateRoleRequestToJSON(value?: UpdateRoleRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
        'permissions': RolePermissionsToJSON(value['permissions']),
    };
}

