/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateIncidentCategoryRequest
 */
export interface UpdateIncidentCategoryRequest {
    /**
     *
     * @type {string}
     * @memberof UpdateIncidentCategoryRequest
     */
    categoryId: string;
}

/**
 * Check if a given object implements the UpdateIncidentCategoryRequest interface.
 */
export function instanceOfUpdateIncidentCategoryRequest(value: object): value is UpdateIncidentCategoryRequest {
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    return true;
}

export function UpdateIncidentCategoryRequestFromJSON(json: any): UpdateIncidentCategoryRequest {
    return UpdateIncidentCategoryRequestFromJSONTyped(json, false);
}

export function UpdateIncidentCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIncidentCategoryRequest {
    if (json == null) {
        return json;
    }
    return {

        'categoryId': json['category_id'],
    };
}

export function UpdateIncidentCategoryRequestToJSON(value?: UpdateIncidentCategoryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'category_id': value['categoryId'],
    };
}

