/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateCategoryRequest
 */
export interface UpdateCategoryRequest {
    /**
     *
     * @type {string}
     * @memberof UpdateCategoryRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateCategoryRequest interface.
 */
export function instanceOfUpdateCategoryRequest(value: object): value is UpdateCategoryRequest {
    return true;
}

export function UpdateCategoryRequestFromJSON(json: any): UpdateCategoryRequest {
    return UpdateCategoryRequestFromJSONTyped(json, false);
}

export function UpdateCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCategoryRequest {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateCategoryRequestToJSON(value?: UpdateCategoryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
    };
}

