/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateProfileRequest
 */
export interface UpdateProfileRequest {
    /**
     *
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    username?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    bio?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    profilePictureUrl?: string | null;
}

/**
 * Check if a given object implements the UpdateProfileRequest interface.
 */
export function instanceOfUpdateProfileRequest(value: object): value is UpdateProfileRequest {
    return true;
}

export function UpdateProfileRequestFromJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestFromJSONTyped(json, false);
}

export function UpdateProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequest {
    if (json == null) {
        return json;
    }
    return {

        'username': json['username'] == null ? undefined : json['username'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'profilePictureUrl': json['profile_picture_url'] == null ? undefined : json['profile_picture_url'],
    };
}

export function UpdateProfileRequestToJSON(value?: UpdateProfileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'username': value['username'],
        'bio': value['bio'],
        'profile_picture_url': value['profilePictureUrl'],
    };
}
