/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {IncidentPriority} from './IncidentPriority';
import {IncidentPriorityFromJSON, IncidentPriorityToJSON,} from './IncidentPriority';

/**
 *
 * @export
 * @interface UpdateIncidentPriorityRequest
 */
export interface UpdateIncidentPriorityRequest {
    /**
     *
     * @type {IncidentPriority}
     * @memberof UpdateIncidentPriorityRequest
     */
    priority: IncidentPriority;
}

/**
 * Check if a given object implements the UpdateIncidentPriorityRequest interface.
 */
export function instanceOfUpdateIncidentPriorityRequest(value: object): value is UpdateIncidentPriorityRequest {
    if (!('priority' in value) || value['priority'] === undefined) return false;
    return true;
}

export function UpdateIncidentPriorityRequestFromJSON(json: any): UpdateIncidentPriorityRequest {
    return UpdateIncidentPriorityRequestFromJSONTyped(json, false);
}

export function UpdateIncidentPriorityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIncidentPriorityRequest {
    if (json == null) {
        return json;
    }
    return {

        'priority': IncidentPriorityFromJSON(json['priority']),
    };
}

export function UpdateIncidentPriorityRequestToJSON(value?: UpdateIncidentPriorityRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'priority': IncidentPriorityToJSON(value['priority']),
    };
}

