/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {IncidentStatus} from './IncidentStatus';
import {IncidentStatusFromJSON, IncidentStatusToJSON,} from './IncidentStatus';

/**
 * 
 * @export
 * @interface UpdateIncidentStatusRequest
 */
export interface UpdateIncidentStatusRequest {
    /**
     * 
     * @type {IncidentStatus}
     * @memberof UpdateIncidentStatusRequest
     */
    status: IncidentStatus;
}

/**
 * Check if a given object implements the UpdateIncidentStatusRequest interface.
 */
export function instanceOfUpdateIncidentStatusRequest(value: object): value is UpdateIncidentStatusRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UpdateIncidentStatusRequestFromJSON(json: any): UpdateIncidentStatusRequest {
    return UpdateIncidentStatusRequestFromJSONTyped(json, false);
}

export function UpdateIncidentStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIncidentStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': IncidentStatusFromJSON(json['status']),
    };
}

export function UpdateIncidentStatusRequestToJSON(value?: UpdateIncidentStatusRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': IncidentStatusToJSON(value['status']),
    };
}

