/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API for Secure Incident. A user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {UserSearchResult} from './UserSearchResult';
import {UserSearchResultFromJSON, UserSearchResultToJSON,} from './UserSearchResult';

/**
 *
 * @export
 * @interface UserSearchResponse
 */
export interface UserSearchResponse {
    /**
     *
     * @type {Array<UserSearchResult>}
     * @memberof UserSearchResponse
     */
    users: Array<UserSearchResult>;
}

/**
 * Check if a given object implements the UserSearchResponse interface.
 */
export function instanceOfUserSearchResponse(value: object): value is UserSearchResponse {
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function UserSearchResponseFromJSON(json: any): UserSearchResponse {
    return UserSearchResponseFromJSONTyped(json, false);
}

export function UserSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSearchResponse {
    if (json == null) {
        return json;
    }
    return {

        'users': ((json['users'] as Array<any>).map(UserSearchResultFromJSON)),
    };
}

export function UserSearchResponseToJSON(value?: UserSearchResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'users': ((value['users'] as Array<any>).map(UserSearchResultToJSON)),
    };
}
