/* tslint:disable */
/* eslint-disable */
/**
 * Secure Incident API
 * Core API draft for the first implementation stage of Secure Incydent. This version follows the domain rule that a user can belong to many projects, but only within one organization or in private projects.
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserSearchResult
 */
export interface UserSearchResult {
    /**
     *
     * @type {string}
     * @memberof UserSearchResult
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof UserSearchResult
     */
    username: string;
}

/**
 * Check if a given object implements the UserSearchResult interface.
 */
export function instanceOfUserSearchResult(value: object): value is UserSearchResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserSearchResultFromJSON(json: any): UserSearchResult {
    return UserSearchResultFromJSONTyped(json, false);
}

export function UserSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSearchResult {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'username': json['username'],
    };
}

export function UserSearchResultToJSON(value?: UserSearchResult | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'username': value['username'],
    };
}

