"""add_incident_helpers_table

Revision ID: cddb7a16613a
Revises: 9f3548d1fdf0
Create Date: 2026-06-18 01:53:03.912561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cddb7a16613a'
down_revision: Union[str, None] = '9f3548d1fdf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_helpers_user_id', table_name='incident_helpers')
    op.drop_index('ix_incident_helpers_incident_id', table_name='incident_helpers')
    op.drop_table('incident_helpers')
    # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_helpers',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'user_id')
    )
    op.create_index('ix_incident_helpers_incident_id', 'incident_helpers', ['incident_id'], unique=False)
    op.create_index('ix_incident_helpers_user_id', 'incident_helpers', ['user_id'], unique=False)
    # ### end Alembic commands ###
