"""added invalidation token

Revision ID: 9f3548d1fdf0
Revises: 9ca2bc071d3d
Create Date: 2026-06-16 13:25:58.524060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3548d1fdf0'
down_revision: Union[str, None] = '9ca2bc071d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
