"""Consolidate invitation model

Revision ID: 8557b1f01d8a
Revises: 0001_initial
Create Date: 2026-05-30 13:18:57.607995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8557b1f01d8a'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_invites', type_='foreignkey')
    op.drop_constraint(None, 'organization_invites', type_='foreignkey')
    op.drop_index('ix_organization_invites_project_id', table_name='organization_invites')
    op.alter_column('organization_invites', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('organization_invites', 'role_id')
    op.drop_column('organization_invites', 'project_id')
    op.drop_column('organization_invites', 'scope')
    # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_invites', sa.Column('scope', sa.String(length=20), server_default='ORGANIZATION', nullable=False))
    op.add_column('organization_invites', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('organization_invites', sa.Column('role_id', sa.UUID(), nullable=True))
    op.alter_column('organization_invites', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_organization_invites_project_id', 'organization_invites', ['project_id'], unique=False)
    op.create_foreign_key(None, 'organization_invites', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'organization_invites', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
